makefile
qrack.hpp

Allow specifying ENABLE_OPENCL on the command line to control enabling or
disabling OpenCL on the command line.  The default in the Makefile remains as
'enabled'.
Example command line:
```bash
$ make
...
$ ENABLE_OPENCL=0 make
...
$ ENABLE_OPENCL=1 make
...
$
```

Support building for non-OpenCL targets

---

qregister.cpp
qregister.hpp

(See also the corresponding pull request under the vm6502q project.)
This is a very simple change. Though Grover's search algorithm worked in the last branch, the carry flag behavior for CMP was absent. Now, carry functions like the other flags, causing a phase shift in quantum mode if the flag is already set, instead of being set by CMP as in classical mode. This allows amplitude amplification searches for operations by a less-than/greater-than criterion.
Additionally, flag-setting logic was parallelized, and clang-format was run.

Correcting CMP carry flag behavior

---

complex16simd.cpp
complex16simd.hpp
example.cpp
makefile
qregister.cpp
qregister.hpp
tests.cpp
tests.hpp

Grover's search can find a subroutine input from which a desired output results, in O(sqrt(m/n)) time for m possible inputs with n matching outputs. While this algorithm is foundational, generalization would make it more useful.
Suppose one qubit register in superposition is used as a coherent quantum memory address offset for loading another register. We assume that the memory we load from is classical but quantum mechanically isolated, (perhaps cryogenically, the cache of a quantum processing unit, "QPU"). Since the classical memory is isolated, currents could potentially pass in coherent superposition between different memory addresses at once, in order to load a superposition into another register. (Superposed currents could be supplied by superconducting interference devices, …

Entangled Hadamard

---

qregister.cl
qregister_opencl.cpp

(In response to https://github.com/vm6502q/qrack/issues/18 )
The big issue was a left shift that should have been a right shift, ("<< 1" should have been ">> 1"). Additionally, a pointer to one of the kernels was wrong. Further, I tidied up all the logic in the course of diagnosing the issue. This passes the test suite.

Fixed seg fault and cleaned up

---

example.cpp
qregister.cpp

Strictly, a quantum logical comparison of two bits requires two separate input bits and a third output bit. Qrack had attempted to handle bit overlap, but not correctly. A safer method might be not to allow bit overlap in logical comparison at all. However, 4 cases of overlap could be made sensible:
1. If all three bits to an AND are the same bit, the intended comparison is equivalent to leaving the bit unaltered.
2. If all three bits to an OR are the same bit, the intended comparison is equivalent to leaving the bit unaltered.
3. If the two input bits to an XOR are distinct, but either is the same as the output bit, the intended comparison is equivalent to CNOT from the exclusively input bit to the input/output bit.
4. If all three bits to an XOR are the same bit, this implies 0 bit …

Fixing unitarity in logical comparisons

---

qregister.cpp
qregister.hpp
tests.cpp

The intent of "EntangledH" was to reverse a lookup table. It fails at this application. It is superfluous to practical application, and it has been removed. All projects in the organization have had corresponding branches opened to remove this method. Grover's search has been tested and still works, but it has not been generalized to invert a lookup table.

Removing 'entangled Hadamard'

---

Makefile
README.md
complex16simd.hpp
doxygen.config
par_for.cpp
par_for.hpp
qregister.cpp
qregister.hpp
qregister_software.cpp
tests.cpp
tests.hpp

* Refactor the duplicate implementations of the different `par_for` methods
* Adjust comments in the header to unify on a style

Refactor the parallel for functions

---

include/qengine_cpu.hpp
include/qinterface.hpp
include/qunit.hpp
src/qengine/gates.cpp
src/qengine/qengine.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp

This fixes the matrix multiplication based controlled gates. The old implementations were based on a misunderstanding of permutation vector numbering convention. This was easily corrected.
However, similar logic was tested for "Swap" and failed. The swap gate has been left as the length=1 case of the register method.

Fixing controlled gate matrix operations

---

include/qunit.hpp
src/qengine/state/operators.cpp
src/qunit.cpp

This only replaces ROL/ROR in QUnit with swap-based versions that are virtually free compared to other quantum gates in QUnit. All shift operations should see a major improvement. It also safe to assume that these operations don't entangle any bits, as is manifest in a swap-based implementation.

Fixing partial collapse of entanglement and Qunit optimization

---

src/qengine/state/opencl.cpp

The state buffer needs both read and write mapping and initialization. Likely, we didn't notice an issue on test systems because OpenCL accepted our host pointer without reallocation and copying. Hence, our host pointer worked as normal, but OpenCL might make unsafe optimizations if it is not given the correct flags.

Fixing over-constrained READ/WRITE flags

---

src/qengine/state/opencl.cpp

nStateVec buffer should be mapped for read to ensure that effects of kernel execution have been waited on and synced.

Fixing read/write flags

---

src/common/oclengine.cpp
src/qengine/state/opencl_multi.cpp

For VirtualCL, this lets multiple devices on different nodes build for the same (virtual) OpenCL context.

Multi-device platform bug

---

src/common/oclengine.cpp

This fixes a bug, when multiple devices are present in the same OpenCL platform.

Fixing multi-device OCL platform initialization

---

include/common/oclengine.hpp
include/qengine_opencl.hpp
src/qengine/opencl.cpp

Simplifies code without hurting performance. (Attempt at manually using device global memory might be redundant with OpenCL compilation.)

Remove usedevicemem

---

include/qinterface.hpp
include/qunit.hpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/tests.cpp

This fixes a bug found in QUnit while implementing a modulo exponentiation example. For convenience, it also adds an inverse "QFT" method.

QUnit bug fix and Inverse Quantum Fourier Transform

---

include/common/complex8x2simd.hpp
src/qengine/state.cpp

Reversing the initialization components of ComplexUnion gives parity with all other implementations, for effective order of input matrices.

Reverse Complex2 components

---

CMakeLists.txt
include/common/bitbuffer.hpp
include/qfusion.hpp
src/common/bitbuffer.cpp
src/qfusion.cpp
test/tests.cpp

This PR lets QFusion be used, semantically, as a temporary optimizing buffer layer on top of any QInterface.

QFusion semantics

---

README.md
include/common/bitbuffer.hpp
include/qfusion.hpp
src/common/bitbuffer.cpp
src/qfusion.cpp

QFusion might buffer multiple gates that should compose as the identity matrix. For example, two X gates on the same bit should buffer as (approximately or exactly) the identity matrix. If a buffer needs to be flushed after composing just two X gates, for example, the buffer gate need not be applied at all. This scenario might actually be relatively common.
In this PR, when we start a buffer flush, we check if the buffer is (approximately or exactly) equal to the identity. If it is, we simply discard the buffer instead of applying it, to give the same result. This works with single bit gates, arithmetic gates, and the controlled variants of both those types.

QFusion Optimization - Discard Buffered Identity Operator

---

include/qengine_opencl.hpp
include/qunitmulti.hpp
src/qengine/opencl.cpp
src/qunitmulti.cpp

Most of the additional overhead for QUnitMulti in the unit tests is redistribution of single bit engines. If we only redistribute large separable blocks, we might efficiently distribute to multiple devices, if we leave any small separable systems on the device they start out on.

QUnitMulti Optimization

---

test/test_main.cpp

This makes the unit test CLI parameters much easier to use. "Layer [types]" and "Proc[essor types]" are selectively enabled by specifying arguments. The default is all layers and all types. If any layers are specified, only those layers are run. If any processor types are specified, only those processor types are run.

Better unit test CLI

---

include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qfusion.cpp
src/qunit.cpp
src/qunitmulti.cpp
test/benchmarks.cpp

This branch gives the user the option to rely entirely on OpenCL device memory, for QEngineOCL. It gives a significant speed boost to the unit tests, to use only device memory. Additionally, it potentially frees GB of memory in general heap, as general RAM no longer needs to be used for state vector allocation.
The original behavior is entirely recovered by constructing the QEngineOCL with "useHostMem = true." Stability might become an issue at the limits of device RAM usage and processing workload, but then the option can simply be toggled with this Boolean. Device memory might be limited to 8GB or significantly less, but QEngineOCL falls back to host memory allocation if it cannot allocate a large enough segment of RAM, and, again, the original behavior can be entirely recovered with …

Device-memory-only option for QEngineOCL

---

include/qunit.hpp
src/qengine/qengine.cpp
src/qunit.cpp
test/benchmarks.cpp

This is a temporary-to-permanent fix for a sporadically failing CRT unit test, with variants of QEngineCPU. The test failed on very roughly 1 out of 100 trials on the test system, but it could be reliably reproduced by iterating the test 1000 times.
The deeper issue might be QEngineCPU's M() method. The commented code in QUnit's ApplyEitherControlled should be theoretically safe, but it fails seemingly specifically with QUnit, QEngineCPU variants. I also noticed that additional isPhaseDirty logic should be added. None of this hurts performance on QFT benchmarks.

Separability debug

---

include/qengine_opencl.hpp

The deallocation in the QEngineOCL deconstructor has never been right. This fixes it, and it also anticipates moving the "normBuffer" into device memory.

Fixing QEngineOCL deconstructor

---

include/common/qrack_types.hpp
include/hamiltonian.hpp
include/qinterface.hpp
src/qinterface/operators.cpp
src/qinterface/protected.cpp
src/qinterface/rotational.cpp
test/tests.cpp

For generality of time evolution Hamiltonians, it is necessary to form exponentiations of the products of gates. This can done if a matrix logarithm gate is available. (The product of exponentiations of commuting gates otherwise can only be equivalent to the exponentiation of their sum, not their product.)
We get this logic "for free," after having already added gate exponentiation, but this still needs to be tested.

WIP: Adding logarithm of gate method

---

CMakeLists.txt
cmake/Examples.cmake
cmake/OpenCL.cmake
examples/grovers.cpp
examples/grovers_lookup.cpp

This adds two basic Grover's search examples.
(This branch is based on cohere_compose_naming, which I realize is strange, now. I'm trying to train new Git habits, but it's difficult.)

Grover's Examples

---

include/common/qrack_types.hpp
include/qengine_opencl.hpp
src/common/qengine.cl
src/qengine/opencl.cpp
test/tests.cpp

This fixes a couple of critical bugs identified while testing Compose/Decompose/Dispose/TryDecompose on systems with smaller device memory limits. This fixes edge cases, when the state vector changes from too large to fit on an OpenCL device to small enough and vice versa. It should also fix issues with cross-device calls to these methods, including memory leaks.

Compose(): useHostMem and cross-device debugging

---

src/qengine/opencl.cpp

GetQuantumState() reads from the state vector, rather than writing to it.
The OpenCL code is often fairly insensitive to these flags, in a lot of cases, but they are necessary to guarantee the expected behavior in total generality.

Wrong OCL flag in GetQuantumState

---

include/common/oclengine.hpp

The OpenCL 2.x headers should be used. However, this already compiles on my Ubuntu 18.04 system. See #134 .

Replacing cl.hpp with cl2.hpp

---

include/common/qrack_types.hpp
include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qfusion.cpp
src/qunit.cpp
src/qunitmulti.cpp
test/accuracy_main.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.hpp

There should be an easy way to switch the random number generator engine, at will. With this branch, the user can change the definition of "qrack_rand_gen" in a single header and replace the random number generator everywhere. While we're at it, the Mersenne twistor generator is probably a better engine to use by default.
I have tested that this passes all unit tests.

Abstracting out random engine, and replacing with Mersenne twistor

---

cmake/Examples.cmake
cmake/OpenCL.cmake
doxygen.config
examples/ordered_list_search.cpp
include/common/qrack_types.hpp
include/qfusion.hpp
include/qinterface.hpp
src/qfusion.cpp
src/qinterface/protected.cpp
test/tests.cpp

(This branch was intended to tie up small loose ends for version 3.1, but I identified a large bug in QFusion the process. Apologies for the combined PR, but please tolerate it. Additionally, our CI just failed on pulling Ubuntu firmware packages, it looks like. We can talk about how to clean this up.)
In preparation for the 3.1 release, a critical bug has been fixed at the buffering threshold in QFusion, per #137 . Additionally, the ordered list search unit test ("quaternary search") has been pulled out into an example, and the Doxygen release number has been updated.

QFusion buffering threshold bug

---

src/qengine/opencl.cpp

It is not safe for a LockSync()/UnlockSync() block to return before mapped buffers are finished copying and being unmapped. Retaining a mapped buffer potentially leads to further operations being ignored, until the unmapping returns. (This bug was noticed in the context of writing amplitudes directly to the state vector in the context of ProjectQ.)

Locksync bug (#2)

---

include/qinterface.hpp
src/qinterface/gates.cpp

This adds a default implementation for `UniformlyControlledSingleBit()` to QInterface.
Default implementations like these (all of which rely only on calls back into other parts of the public interface) ease the process of adding new engine types and debugging optimized reimplementations of methods.
(This implementation has been used to test a bug in the ProjectQ integration. Relying on this default, it seems that the optimized implementations of `UniformlyControlledSingleBit` do not significantly differ from this decomposition in numerical result. The reason for the ProjectQ bug has not been identified, but this helps rule out bad optimized implementations, as the culprit.)

Default UniformlyControlledSingleBit

---

include/common/oclengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
src/qengine/opencl.cpp

This addresses the findings of https://github.com/doe300/VC4CL/issues/55:
1. QEngineCPU used the wrong deallocator for its state vector (`delete[]` instead of `free()`).
2. `cl::Event` objects should be treated as unique references and not duplicated between our "soft queue" and stack instances.
3. `clear()` should not be called on our running queue of `cl::Event` objects as a `std::vector`, to avoid invoking the destructor on each event prematurely.
Addressing these three issues, it seems that the VC4CL build for Raspberry Pi works without build-specific `clFinish()` calls.

Wait events debug

---

README.md
include/qengine_opencl.hpp
src/qengine/opencl.cpp
src/qinterface/protected.cpp
test/tests.cpp

Uniformly controlled gates hang for an indefinite amount of time, on the Raspberry Pi 3. I will continue to profile this, but this might simply be at the limits of the hardware. For `n` control bits, these operation are equivalent to `2^n` parallel gates, which is extreme. If just the uniformly controlled gates are made to wait on finishing the queue, before and after kernel dispatch, this behavior resolves.

Debugging on Raspberry Pi

---

src/qengine/opencl.cpp
src/qinterface/gates.cpp
test/tests.cpp

I noticed that our Mac build stopped working, and, when the build was fixed, it failed a couple of unit tests. I diagnosed and addressed the issue, here. The build error was a warning (with `--Wall --pedantic`) that really isn't significant. The unit tests failures were slightly nasty, though.
`enqueueReadBuffer` throws an exception (sometimes) when trying to read from a buffer that is allocated host-side. Forcing the buffer to map to the allocated array, instead of reading into a different array, fixes the issue. This _might_ be a strict requirement of OpenCL host code with host-side allocated arrays, which we violated. Strangely, the same hardware does this just fine on the Linux boot side of its Mac/Linux dual boot, and it hasn't been an issue anywhere else.
There will be a small to …

Debugging on Mac

---

CMakeLists.txt
README.md
cmake/Examples.cmake
cmake/OpenCL.cmake
include/common/complex16simd.hpp
include/common/complex16x2simd.hpp
include/common/complex8x2simd.hpp
include/common/oclengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qinterface.hpp
src/common/parallel_for.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qinterface/protected.cpp
test/tests.cpp

In an effort to test this on a Windows machine with an AMD, I debugged our Windows build and unit tests. This passes all tests on the Windows partition of my primary development machine, except for the noted issue with `ApproxCompare()`. Windows 10 has OpenCL drivers for all of my devices, so this gave me an opportunity to test and debug a configuration with 3 devices on 2 platforms.

Debugging on Windows and cross-device

---

src/qunit.cpp

This appears to have been the problem with ApproxCompare(). The problem and the fix are manifestly simple.

Fixing bug in QUnit ApproxCompare()

---

CMakeLists.txt
cmake/Examples.cmake
cmake/OpenCL.cmake
examples/quantum_associative_memory.cpp
examples/quantum_perceptron.cpp
include/qneuron.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qinterface/protected.cpp
test/tests.cpp

This PR adds a (header-only) `Qrack::QNeuron` class, with an example. `QNeuron` is a simple single neuron instance that can learn and predict in superposition, for machine learning. Optimal algorithms and good applications have not yet been determined.

Simple QNeuron example

---

include/common/qrack_types.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qinterface/protected.cpp
test/tests.cpp

I looked over the common types/macros, and this is the only one that worries me, at the current stage of development. We've dropped the custom double complex type, since it was bugged, since it only gave a benefit to QEngineCPU, and since the x2 vector type optimizations work just fine with the `std::complex` types. Given this, it's no longer necessary to have this macro. It only clutters up the space with a reserved symbol that I could see becoming a problem.
I'll invite other opinions, while we're on the topic, but I think all the other macro type definitions are specific enough to Qrack, and very unlikely to be otherwise desired for custom symbols, that they can (and should) remain as they are.

Removing polar() macro

---

include/qneuron.hpp
src/qinterface/rotational.cpp
test/tests.cpp

It is commonly not necessary to update every variational parameter in a `QNeuron` on a learning iteration--only one parameter, on a non-superposed permutation.
Additionally, a bug was discovered in uniformly controlled gates, where a `bitLenInt` type was used where the expected range required a `bitCapInt`.

Optimizing and debugging QNeuron

---

include/qneuron.hpp

It's useful to be able to get and set QNeuron angles (model parameters) in order output trained models and set the initial state for hybrid training.

QNeuron get/set angles

---

examples/quantum_associative_memory.cpp
examples/quantum_perceptron.cpp
include/qinterface.hpp
include/qneuron.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qinterface/protected.cpp
test/benchmarks_main.cpp
test/tests.cpp

It seems to make more sense to start the default of any untrained QNeuron state as returning a 0.5/0.5 probability superposition of true and false. "Eta" will not be rescaled, since 0.5 still trains up to 0.5 probability in one step, which is full training, and 1.0 trains exactly 0 to exactly 1, or vice versa. `Learn()` (as opposed to `LearnPermutation()`) might find limited use, now, but it was already replaced for training on permutations, and it might still be appropriate in the case that training data is loaded in superposition.

Baseline of QNeuron output set to 0.5/0.5 superposition

---

.travis.yml
include/qneuron.hpp
test/tests.cpp

Based on experiments with training QNeuron networks, changes have been made to the class, focusing on its initial conditions. Additionally, a bug has been fixed in the indexing of variational angles in LearnPermutation().
(Benn is not available to review this PR.)

QNeuron initial conditions

---

CMakeLists.txt
README.md
cmake/RDRand.cmake
include/common/rdrandwrapper.hpp
include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
src/common/rdrandwrapper.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qfusion.cpp
src/qunit.cpp
test/accuracy_main.cpp
test/benchmarks_main.cpp
test/test_main.cpp

Turns out, there's a hardware source of entropy available in relatively recent Intel and AMD chips. This PR gives the option of using the RDRAND instruction, if it's available.
(I cannot promise anything at all, as far as the quality or nature of this generator. However, I read some background on it, including a Stack Overflow answer from someone claiming to be one of the original developers, and the generator _might_ be semi-quantum random in nature. There's a base hardware entropy generator which could reasonably be quantum in nature. If the throughput demanded from the RDRAND instruction is too high, it uses the base hardware entropy source to seed a "cryptographically secure" pseudo-random-generator. Alternatively, for low rates of generation demand, the base entropy source is used …

RDRAND option

---

include/hamiltonian.hpp
src/qinterface/operators.cpp
test/tests.cpp

One of the fastest, simplest, and most direct ways to specify an interacting Hamiltonian should be via "uniformly controlled gates." This does use somewhat more memory, though. Having the option to specify a Hamiltonian (component) this way could greatly reduce demand on the labor of users writing quantum time evolution simulations.

Adding uniformly controlled gates to Hamiltonian simulation

---

include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qfusion.cpp
src/qunit.cpp

For a change in the ProjectQ integration, the parameter of SetQuantumState() should be const. (It is already treated as such within the method bodies.)

Change SetQuantumState() parameter to const

---

include/qengine.hpp
include/qinterface.hpp
include/qunit.hpp
src/qengine/gates.cpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qinterface/gates.cpp
src/qinterface/rotational.cpp
src/qunit.cpp
test/benchmarks.cpp

The "isProbDirty"-related optimization of QUnit can be carried further. Many common quantum gates will transform the permutation basis probability in a simple predictable way, such that it is not necessary to "dirty" the bits affected. This avoids costly permutation probability checks, by preserving the cache under classical transformations.
We seem to already have an improvement on the QFT, from this. I'll carry this type of optimization as far as I reasonably can, before I mark this PR ready for review.

QUnit permutation probability optimization

---

include/qinterface.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
test/tests.cpp

This adds the "U" and "U2" gates, as commonly defined.
These are extremely convenient, because the parameters of U cover all unitary single bit gates, and therefore all possible _valid_ single bit gates, and all values of the angle parameters are also valid.

U and U2 gates

---

src/qengine/opencl.cpp

The "powersBuffer" is loaded if and only if there are more than two bits involved in the gate.

Fixing Apply2x2() controls bug

---

include/qengine_opencl.hpp
src/common/qengine.cl
test/benchmarks.cpp
test/tests.cpp

Often, we use a series of single complex multiplications (`zmul()`) to accomplish the common task of multiplying a 2x2 complex matrix by a 2 component vector. The OCL compiler(s) could probably optimize this, except it's harder given the bounds of the function closure.
Sure enough, if we pull the whole matrix multiplication operation into its own function, we get both a general speed boost and a significant reduction in CPU binary size. Most modern GPUs are based on "warp" units, I think, which don't use SIMD, though simply pulling the entire operation into the same closure gives the GPUs' compilers more chance to optimize. The large reduction in CPU binary size, however, is probably because the compiler is now able to effectively reduce this task to SIMD instructions, also increasing …

Vectorizable OCL matrix multiplication

---

include/qunit.hpp
src/qunit.cpp

This branch originally started as an attempt to debug for the Raspberry Pi 3, by fixing an unsafe pointer, under certain conditions. Fixing that pointer, this lead to a series of optimizations for controlled gates, and controlled arithmetic in particular. In many cases, this could greatly improve the efficiency of Shor's algorithm, and general QUnit efficiency.

More QUnit optimization (and pointer safety)

---

include/qunit.hpp
src/qengine/operators.cpp
src/qunit.cpp

This branch checks whether arithmetic registers in QUnit are already sufficiently separated to effectively carry out integer arithmetic classically. The primary upthrust of these optimizations is that arithmetic operations can be used to quickly initialize register states without auxiliary classical "gate fusion" optimization. In the case that even one quantum arithmetic operation is avoided (say, an addition operation on an 8 or 16 bit register,) these optimizations probably return a speed gain.
This is not an exhaustive separability arithmetic optimization PR, and more work is planned for this weekend and coming week. Tests have shown me that the separability optimizations of QUnit work best (or only) when entangled separations are _proactively_ _avoided_, rather than reduced …

QUnit arithmetic separability

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

QUnit is generally based on an approach like "stabilizer" quantum circuits. (See https://arxiv.org/abs/quant-ph/0406196.) Compared to other stabilizer engines like it, QUnit has a few advantages:
- On demand, it exceeds the limitations of Clifford gates, to encompass an essentially unconstrained gate set.
- Its theory recovers polynomial time executions and RAM savings **_beyond_** strict, common stabilizer simulators, (though also see related papers referenced in the introduction of the above paper by Vidal, Valiant, and Ter-hal and DiVincenzo, etc.)
- It represents the quantum state as a vector and does not rely on the use of "stabilizer matrices"
(QUnit was originally based on "Breaking the 49-qubit barrier," by Pednault et al., https://arxiv.org/abs/1710.05867, for reference) …

QUnit stabilizer optimization

---

src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qengine/state.cpp

I debugged ProjectQ support, today, and I diagnosed issues with that stack. A PR will be coming immediately on the Qrack fork of ProjectQ.
On the Qrack side of this process, we have a small internal refactor. Here's the standard I suggest for signed versus unsigned literals:
- Integral 0 literals should be signed, for simplicity. `0` implies signed 0.
- Integral 1 literals throughout the library should probably almost universally be unsigned 1, "`1U`."
- Floating point types should rely on `ONE_R1` and `ZERO_R1`.
This is premature, but it should be the guideline. `bitLenInt` and `bitCapInt` are unsigned types. Nothing in the library depends on the sign of 0, so terseness is preferable. Bit shifting patterns are used ubiquitously as `(1U << qubitIndex) - 1U`, and the safest and most …

Cleanup (concomitant with ProjectQ debugging)

---

include/qinterface.hpp
include/qunit.hpp
src/common/qengine.cl
src/common/qheader32.cl
src/common/qheader_double.cl
src/common/qheader_float.cl
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qunit.cpp

I am debugging Compose()/Decompose() for ProjectQ, while attempting to track down a numerical inaccuracy ProjectQ's decompositions with QUnit.
This led me to rethink the Decompose() algorithm. I think it works fine, under the assumption that the sub-units requested are actually already ideally separable. However, then, only relative phases _within_ the separable units should matter, not their global phase offsets relative each other. The part of the algortihm that adjusts the global phase offset against some particular gauge is confusing and expensive. I think the primary reason I had it in there was for round-trip with ApproxCompare() in TryDecompose(). However, if we offload the check for an arbitrary global phase offset into ApproxCompare(), not only do we optimize the much more …

Debugging Decompose (for ProjectQ)

---

include/qunit.hpp
src/qunit.cpp

This pull request adds two general types of optimizations to QUnit:
- If the constructor flag was set to indicate that overall phase factors are arbitrary, phase gates are skipped when a qubit is in a |0>/|1> eigenstate.
- If a qubit is being manipulated in such a way that the starting point and a sequence of operations is analogous to manipulating a classical bit, the classical bit state is cached. Operations are carried out directly on the classical cache, and we avoid dispatching the underlying simulation. (The cached value is loaded back into the qubit simulator, when generality is needed and classical emulation cannot continue.)
The point is, neither of these optimizations should have physical consequence, in terms of real-valued observables, (i.e. the expectation values of Hermitian …

QUnit classical bit emulation

---

include/qengine.hpp
include/qinterface.hpp
src/common/parallel_for.cpp
src/qengine/arithmetic.cpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qinterface/gates.cpp
src/qinterface/rotational.cpp

As a hypothetical, I tried to switch in a software-based 256-bit integer type `bitCapInt`, and this is the core of the compiler incompatibility I found.
It is not actually feasible to represent 2^256 amplitudes, or anywhere close. However, with QUnit, large numbers of low entanglement qubits are feasible, depending on the `bitCapInt` and particularly `bitLenInt` types. My hope is that, though permutations can't be specified as a single integral type, despite the API definition, it should be possible to allocate many low-entanglement qubits and manipulate them per the gate model.

Type safety and standardization

---

include/qinterface.hpp
include/qunit.hpp
src/qinterface/arithmetic.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/tests.cpp

This PR adds Draper arithmetic to QInterface. (See https://arxiv.org/abs/quant-ph/0008033.) To make it work, I had debug the QFT and its inverse, which I realized have been wrong for a long time. A unit test was added specifically for a very  limited case of Draper arithmetic.
The point was to optimize QUnit arithmetic by performing it via the gate model. However, this might have been somewhat for naught; it seems like the dyadic fractions used in that algorithm might lead to too great inaccuracy for Grover's searches of sizes of 8 to 16 qubits carried out in the unit tests. This led me to find another way to optimize QUnit arithmetic. It turns out, going directly by the classical full adder truth table, there are still many cases with superposition where adding a classical integer might …

QUnit Arithmetic

---

src/qunit.cpp

I'll decide whether I want to store probability and phase as two pseudo-amplitudes, (where phase might be invalid,) act on that decision, and merge in.

QUnit: Can cache ApplySingleBit()

---

include/qunit.hpp
src/qunit.cpp

In QUnit, checking whether all controls are in permutation basis eigenstates lets us catch the case where UniformlyControlledSingleBit() is equivalent to ApplySingleBit(), avoiding _all_ representational entanglement for virtually no cost. For neural net scripts I have experimented with, this should commonly reduce fitting times to the logarithm of their original fitting cost.
Avoiding entangling _some_ but not _all_ of the bits is a trickier and thornier case. To avoid one bit of entanglement, we limit to 3/2 the RAM use for the gate matrix definition plus a reduced copy, where the original gate arguments could already be the same size as the fully entangled state vector. Once any degree of entanglement sets in, each additional qubit basically adds a factor of 2 to execution time and …

Simple QUnit UniformlyControlledSingleBit() optimization

---

CMakeLists.txt
README.md
cmake/VM6502Q.cmake
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
src/common/qengine.cl
src/qengine/arithmetic.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qfusion.cpp
src/qinterface/gates.cpp
src/qinterface/protected.cpp
src/qunit.cpp
test/tests.cpp

These methods were optimized via two routes:
- Usually, it not necessary to calculate an expectation value for the returned results of these methods. This is usually only needed for debugging with the VM6502Q disassembler. A CMake flag has been added to restore this behavior, but it is off by default.
- Similar to `UniformlyControlledSingleBit()`, it's possible to optimize the base cases of these methods. I do not expect this to be a common use case, but it's hard to anticipate what won't be entered as inputs in QUnit.

Bit skipping for UniformlyControlledSingleBit; IndexedLDA/ADC/SBC optimization

---

CMakeLists.txt
include/common/parallel_for.hpp
include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
include/statevector.hpp
src/common/parallel_for.cpp
src/qengine/arithmetic.cpp
src/qengine/gates.cpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qengine/state.cpp
src/qengine/utility.cpp
src/qfusion.cpp
src/qunit.cpp
test/test_main.cpp
test/tests.cpp

Benn, I'm going to need your oversight, for this.
I'm experimenting with an option for a sparse state vector, in QEngineCPU. This would typically only be useful in the context of QUnit.
Naively, a sparse state vector can be a bad approach. Applying Hadamard gates across every bit in a coherent unit of qubits fills every permutation basis ray with a nonzero value. However, with QUnit optimizations, this doesn't cause the sparse occupancy to blow up, because every one of those bits is _separable_. With QUnit, the RAM still scales like `2*n` for `n` qubits, in that case. Separability optimization in QUnit opens the possibility of significant RAM savings with a sparse array for a state vector. With or without QUnit, I have an example case in mind.
Say that we wanted to apply amplitude …

Adding QEngineCPU option for sparse state vector

---

include/qunit.hpp
src/qunit.cpp

This fixes the broken CI, for |+>/|-> basis optimizations.

Debugging CI

---

include/qfusion.hpp
include/qinterface.hpp
src/qfusion.cpp
src/qinterface/arithmetic.cpp
test/tests.cpp

This is to clean up the work from last week. `FullSub`/`SBC` were wrong and have been removed, for now. Controlled `FullSub`/`ADC` variants were added, but these are QInterface-only implementations, (no optimized variants). Tests have been copied and slightly modified from the non-controlled variants.

Removing quantum-to-quantum-subtraction; adding controlled FullAdd

---

src/qunit.cpp

This PR removes a debugging statement in QUnit::Z(), which should have been taken out after testing.

Removing QUnit::Z() debugging

---

include/qfusion.hpp
src/bitbuffer.cpp
src/qfusion.cpp
src/qinterface/protected.cpp
test/tests.cpp

QFusion was missing most of its opportunities for fusion optimizations, in order to cover bugs. The underlying bugs have been fixed, allowing the optimizations to be restructured to work as originally intended.

QFusion debugging and optimization

---

test/benchmarks.cpp
test/benchmarks_main.cpp
test/tests.hpp

Per #230, the maximum number of qubits can be selected from the command line. Let me know if you decide you'd also like the minimum configurable, but I'm worried it will lead to confusion and frustration when users set the minimum below 3 or 4 qubits, which is the bare minimum for the general suite. Rather, I also added another Boolean option to run _only_ the maximum qubit count, which saves roughly half the time, on most tests.
Additionally, tests have been "tagged," and tags can be entered on the command line for specific inclusion ("[grover]") or exclusion ("~[grover]"). In part, this serves as a workaround for managing the extremely long-running Grover's algorithm tests.
Entering "-1" for the maximum qubit count parameter, if OpenCL tests will run, attempts to automatically scale the …

Issue #230: Variable qubit selection for benchmarks (and related improvements)

---

README.md
include/qengine.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
include/statevector.hpp
src/qengine/qengine.cpp
src/qfusion.cpp
src/qinterface/protected.cpp
src/qunit.cpp
test/benchmarks_main.cpp
test/tests.cpp

Per issue #200, it'd be great if QUnit could be a super set of "stabilizer" simulators, ex. supporting a classically efficient Clifford group as CNOT, H, and phase gates, at least. For all QUnit already does, it was missing a (terminologically) "efficient" CNOT implementation. This PR should give it one. In fact, separability unit tests had to be updated to accommodate the fact that QUnit can now maintain a separated representation for cases of CNOT which QEngine types can not separate, since they can only do so along permutation basis rays. In a sense, the CNOT improvement is "ad hoc," in that it has not been generalized to more controls or different gate targets, but it does seems to be an at least minimally complete Clifford group.
The documentation should probably be updated to talk …

CNOT optimization ("Gottesman-Knill"); "isEmulated" edge case; phase gate optimization 

---

examples/ordered_list_search.cpp
examples/quantum_perceptron.cpp
include/common/qrack_types.hpp
include/qinterface.hpp
src/common/parallel_for.cpp
src/common/qengine.cl
src/common/qheader32.cl
src/common/qheader_double.cl
src/common/qheader_float.cl
src/qengine/arithmetic.cpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qengine/state.cpp
src/qfusion.cpp
src/qinterface/arithmetic.cpp
src/qinterface/gates.cpp
src/qinterface/protected.cpp
src/qinterface/qinterface.cpp
src/qinterface/rotational.cpp
src/qunit.cpp
test/accuracy.cpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/tests.cpp
test/tests.hpp

This can still be generalized further, but, at least in the case of a single control bit and single target, phase gates are symmetric under swap of the bits. Swapping target and control as convenient for optimization can make a huge difference to more general cases of the QFT.

Controlled phase gate optimization; > 30 qubits fix

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

Per #200, managing to maintain separability in cases of CNOT with H gates (per line 2819 in the [unit tests](https://github.com/vm6502q/qrack/commit/fa76fc899af04823cef884a2c78adf3517c78604)), I wanted to support this optimization for generally controlled single bit gates, as other projects would and do use for a Qrack API.
Checks for identity should be (almost) entirely removed from QUnit, as attempts at optimization. If anywhere, this should go in QFusion. Further, if all I know is that a bit is in "50/50" superposition, it's relatively unlikely that a check that tries a basis conversion with H will place it into |0>/|1>. (Although, it's obvious that it will handle the first two roots of unity, and we might have reason to suspect first roots in particular.)
This is basically just …

CNOT Optimization and Cleanup

---

include/qunit.hpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/tests.cpp

We were failing new ProjectQ unit tests, specifically for amplitude amplification. The reason was that `QInterface::ProbMask` implicitly assumed that there was no conditional dependence between bits, (i.e. entanglement). `ProbMask` is significantly slower, now, but I would have already suggested avoiding this method in the first place; try to treat `QInterface` types like you would an actual quantum computer, for the most part. The equivalent method, if even available, would likely come at a similar premium for overhead.
In the process, I noticed I had confused myself on how `isEmulated` should be used for "shards" in QUnit. At this point, the purpose of `isEmulated` is to take single separated bits that have totally "clean" caches and handle them with "host"/CPU code only, in order to …

ProbMask and isEmulated debugging (for ProjectQ)

---

include/common/qrack_types.hpp
include/qinterface.hpp
include/qunit.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.cpp

QUnit converts freely between |0>/|1> and |+>/|-> bases, by tracking a Boolean for each gate, and commuting applied gates with H where feasible. In this PR, we have implemented commutation with H for CZ, controlled S, controlled T, and their inverses. (CZ is its own inverse.) A bug was corrected in phase gates, earlier, that had caused the QFT benchmarks to regress in performance, but CS and CT commutators seem to recover some of this loss. Maybe more importantly, this seems to point to a general approach for optimizing QFT simulation, by handling commutation with H for singly-controlled phase gates up the n-th root of unity for n qubits in the QFT.
PR #239 attempted to take the work from around the time of #220 and isolate just the second order case. #241 attempted to carry to this to …

Phase gate bit symmetry optimization and debugging (and API extension)

---

include/qunit.hpp
src/qengine/opencl.cpp

(Apologies!) This particular piece of code pertaining to combining symmetric phase gates showed intermittent problems and a lack of coverage. Both the unit tests and the benchmarks run locally, with this piece removed. Waiting for the and further local environment tests, then merging as a hotfix.

Hotfix: Remove control/target symmetry optimization

---

test/accuracy.cpp
test/accuracy_main.cpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/catch.hpp
test/test_main.cpp
test/tests.cpp
test/tests.hpp

Understanding the intended requirement of #245, here's a draft for consideration. Measurement results are output to a binary file. The binary string length in chars is `sizeof(bitCapInt)`, per iteration.

Issue #245: Implementing measurement output option (and updating Catch2)

---

CMakeLists.txt
README.md
cmake/OpenCL.cmake
cmake/UInt128.cmake
examples/quantum_associative_memory.cpp
examples/quantum_perceptron.cpp
examples/shors_factoring.cpp
include/common/qrack_types.hpp
include/qinterface.hpp
src/common/parallel_for.cpp
src/qengine/opencl.cpp
src/qinterface/arithmetic.cpp
src/qinterface/protected.cpp

GCC and clang already offer unsigned 128 bit integral types. These are not compatible with the OpenCL standard, yet. It's possible (or likely) we have an unsafe 64 bit operation to ruin this compatibility, somewhere. However, we handled the 32 bit boundary, and we'll handle the 64 bit boundary, as well, as >64 bit support is demanded. This PR starts us on experimenting with support for more than 64 qubits (when the particular problem is tractable with QUnit).

Experimental uint128_t support

---

.travis.yml
include/qinterface.hpp
include/qunit.hpp
include/statevector.hpp
src/bitbuffer.cpp
src/qinterface/protected.cpp
src/qunit.cpp
test/benchmarks.cpp

This tidies up some work that was left partially finished on phase gate optimization in QUnit. Further, last night, I read "Quantum Circuit Cosmology: The Expansion of the Universe Since the First Qubit" (https://arxiv.org/abs/1702.06959) and I was really impressed by it, and I thought it would make a great benchmark (or set thereof).
In the process of tinkering with QUnit for the benchmark, the ProjectQ unit tests broke. The piece of code that primarily precipitated this starts on line 107 of qunit.cpp. The offending code, however, was line 42, where we had been missing a negation on a check for `randGlobalPhase`. Trying to diagnose and fix that, I corrected a number of sloppy floating point value checks. However, the maximum qubit case of the ProjectQ state preparation decomposition …

Phase optimization (and cosmology benchmark)

---

include/common/parallel_for.hpp
include/common/qrack_types.hpp
include/qengine.hpp
include/qengine_cpu.hpp
include/statevector.hpp
src/common/parallel_for.cpp
src/qengine/state.cpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/tests.cpp
test/tests.hpp

QUnit lacks intrinsic support for fundamentally optimized preparation of Bell pairs, and similar states. To my knowledge, this is the only case missing (from CNOT) in order to cover a full stabilizer (Clifford) algebra.
However, it occurred to me, this one case that QUnit can't handle on its own results in states that are amenable to the "sparse state vector" optimization constructor option. Some minor tweaks to `Prob()` and `Compose()` result in an efficient stabilizer simulator super set!
This optimization isn't a 100% general optimization for QUnit, and it can't operate at all with QEngineOCL, but it's an important case! We might now start to quantify exactly how far we have extended "fundamentally efficient" simulation in QUnit to past and including a full Clifford algebra.

Sparse state vector optimization (Gottesman-Knill)

---

src/qunit.cpp
test/benchmarks.cpp

I wonder whether caching controlled phase gates in QUnit was the most useful optimization, but it at least doesn't have to hurt H gate basis transformation optimizations, we see in this PR. When we need to clear controlled phase gate buffers, I think it's literally not possible to "fuse" them as controlled single bit gates with H gates cached behind them in the queue, but we can transform the controlled phase target to bring the H gate basis transformation to the other side of application of the controlled phase gate. This is actually quite important, for further work basis transformation optimizations.
Additionally, I added a benchmark that randomly selects from a set of gates that can all be executed "efficiently" together, to form random circuits. I believe the set does not fully cover …

H / controlled phase optimization commutation; "solved circuit" demonstration

---

src/qunit.cpp

In playing with benchmarks, I found a memory leak in `QUnit::ApplyControlledSinglePhase()`. I also noticed that this method could easily be redirected to the optimized `CZ()` method, when appropriate.

Fixing memory leak in ApplyControlledSinglePhase

---

include/qinterface.hpp
test/benchmarks.cpp

I missed a usage of `__uint128_t` when the flag is off, and it became apparent in the Windows build. (As far as I know, the C++ compiler for Visual Studio does not support native 128 bit integral types at all.)

Windows debugging

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.hpp

If both phase angles of a cached controlled phase gate are the same, the buffer commutes with H. (Note that this gate can still have physically significant effect with identical angles, since the phase change is only imparted to half the permutations.) Maybe surprisingly, this case occurs with some frequency in the QFT, and we gain a significant average speed improvement on `test_qft_superposition_round_trip`.

TryHCommute() for QUnit controlled phase buffers

---

include/qunit.hpp
src/qinterface/gates.cpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.cpp

If we actually have an efficient alternative implementation of a Gottesman-Knill Clifford algebra, I can't think of any reason we can't throw a gate of arbitrary phase in:
```
$ ./benchmarks --layer-qunit-qfusion --proc-opencl-single --max-qubits=-1 test_solved_universal_circuit
Random Seed: 1575056458 (Overridden by hardware generation!)
Device #0, Loaded binary from: /home/iamu/.qrack/qrack_ocl_dev_0.ir
Device #1, Loaded binary from: /home/iamu/.qrack/qrack_ocl_dev_1.ir
Device #2, Loaded binary from: /home/iamu/.qrack/qrack_ocl_dev_2.ir
Default platform: NVIDIA CUDA
Default device: GeForce GTX 1070
OpenCL device #0: Intel(R) Gen9 HD Graphics NEO
OpenCL device #1: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
OpenCL device #2: GeForce GTX 1070
############ QUnit -> QFusion -> OpenCL …
```

Universal quantum gate set test

---

include/qunit.hpp
src/qinterface/protected.cpp
src/qunit.cpp
test/benchmarks.cpp

Since `QEngineOCL` calls `Finish()` in its own destructor, it should not be necessary for a `QEngineShard` to call `Finish()` in its destructor at all. (At one point, I think this was needed, but it must have been a kludge.)
When combining phase gates in QUnit, we missed a check for whether the second of the two gates combined was `IsInvert`, which blocks combining the gates. This has been fixed.
First priority in QUnit should basically always be to _proactively_ avoid composition of shards in the first place, where it can be avoided. As of yet, virtually no level of complication of "host code" checks is comparable to the exponential cost of composing additional qubits without need. Since special cases have the potential to avoid the application of a composing gate entirely, …

QUnit optimization and minor bug fix

---

include/qengine.hpp
include/qunit.hpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qinterface/arithmetic.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp

This fixes a bug in controlled inversion gates that became apparent while trying to extend new optimizations to be available through our ProjectQ integration repo. (There still seems be an arbitrary global phase factor in the decomposition of uniformly controlled gates through "controlled phase" gates, as opposed to "controlled inversion" gates, but the unit tests have not detected a difference in physically measurable quantities.) Performance is not noticeably reduced.

Controlled inversion debugging (for ProjectQ unit tests)

---

README.md
include/qfusion.hpp
include/qneuron.hpp
include/qunit.hpp
src/common/parallel_for.cpp
src/qengine/arithmetic.cpp
src/qinterface/arithmetic.cpp
src/qinterface/gates.cpp
src/qinterface/operators.cpp
src/qinterface/protected.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/benchmarks.cpp

Mostly, this PR brings intended references to `ONE_BCI` and `pow2()` up to code standards. This might fix issues with certain methods used on `QInterface` instances in excess of about 32 qubits in length.
Additionally, I have added an "optimized" case of `QUnit::ZeroPhaseFlip()`. In practice, when this method is called, entanglement across the length of the register for the operation is probably guaranteed, such that no practical improvement is usually achieved. However, there may be use cases we don't anticipate, where some bits start in |0>/|1> eigenstates when this method is called on them, in which case this change is an improvement in execution time and RAM usage. In any case, there is no practically significant _loss_ of performance from this alternative implementation.

ONE_BCI code standards (and QUnit::ZeroPhaseFlip optimization)

---

src/qinterface/rotational.cpp

I swear to you that I always went to the same pedagogical source for the definition of the Pauli X-axis rotation operator, and the source had it wrong this whole time! I finally noticed the problem when my expectation values for Pauli Y tended to have exactly opposite signs from what was expected, in the Qiskit/Pennylane integration I'm working on. I'll update our unit tests, if they fail in CI. This is slightly complicated to target with a unit test, but the Qiskit/Pennylane unit tests will ultimately cover it, when I add those to the master branch CI.

Fixing RX() convenience method

---

include/qunit.hpp
src/qinterface/gates.cpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.cpp

This PR is intended to achieve parity between `QEngineOCL` vs. `QUnit` pass/fail on Qiskit unit tests. As of opening this WIP, the stats are:
QEngineOCL: 675/253
QUnit: 659/269
Failures for QEngineOCL are assumed to be due to lack of supported features in the Qrack API, (such as noise, instructions like "bfunc," multi-qubit-target multiplexing, and certain forms of measurement). Head of master was 654/274 for QUnit. The bug already fixed was in QUnit phase gate buffering, and this is also likely where the rest of the bugs reside, based on my current understanding. I am not yet sure if the pass/fail rate is deterministic, but I will also determine this, by the end.

Qiskit debug

---

include/qinterface.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
src/qinterface/rotational.cpp
test/benchmarks.cpp
test/tests.cpp

A closer reading of the paper, and an examination of the supplemental materials, point to at least a couple of changes to the "quantum supremacy" benchmark. Firstly, "square root of W" is not "square root of Walsh-Hadamard transform." I think I have the correct definition of this gate and its inverse, now, called `QInterface::SqrtXConjT` in Qrack. Secondly, if I understand a point of the description in one of the figures, which seems compatible with the circuit definitions in the supplemental materials, the same single bit gate is not to be repeated on a qubit in the immediately following iteration.
These changes make no major difference difference in `QUnit` performance. I have also noticed two other differences between our benchmark and that of the original paper, which will probably …

Sycamore benchmark updates (and Rx gate phase sign correction)

---

.travis.yml

The Qiskit provider unit tests pass on my local development system. I've made good progress debugging the installation and build in the CI, and I'll mark this ready for review as soon as we 100% pass on the repo. In the last couple of commits, I think we were passing up to a missing `cvxpy` dependency. Then, setuptools installation failed, (through no fault of ours). A CI build and test is in progress, as I write this, and it might pass.

Full stack unit tests

---

test/benchmarks.cpp

Upon further inspection of the Sycamore benchmark paper's supplemental materials, we need to flip "C" and "D" in our "ABCDCDAB" tiling sequence. Again, this makes no significant difference in `QUnit` performance. I might throw other relevant "tweaks" on top of this, in the PR.
At this point, I think the 54 qubit benchmark in our suite is equivalent to the published Sycamore circuit at depth of 20, upon inspection of the [supplemental materials](https://datadryad.org/stash/dataset/doi:10.5061/dryad.k6t1rj8) for that [paper](https://www.nature.com/articles/s41586-019-1666-5), up to two major differences:
1. The 54th qubit in Google's physical processor instance, which they excluded from the benchmark for noise/performance considerations, is effectively reinserted, in this Qrack benchmark. …

Updating test_quantum_supremacy tiling sequence

---

test/benchmarks.cpp

At one point, `TrySeparate()` seemed to help performance on benchmarks. Some or all of these benchmarks no longer see a benefit from it.
No library code has been changed, just one line of code in the benchmarks. If the CI fails again, I most likely need to optionally xFail sporadic failures in the Pennylane Qiskit plugin, or increase those tests' tolerance.

TrySeparate() hurts performance on benchmarks

---

CMakeLists.txt

The `atomic` library is a default inclusion for most C++11 compilers, but not GCC for the Raspberry Pi 4. Explicitly linking it should not hurt anything.

Explicitly add 'atomic' library for certain compilers (Raspberry Pi 4)

---

.travis.yml
README.md

Between the last PR and this morning, a dependency of some project in the Python stack was updated. I noticed this while attempting to update the README. This lead to an entire chain of events of where I updated the CI Python version and temporarily disabled SimulaQron unit tests.
On the plus side: we're using a newer version of Python for the CI. On the down side, this might or might not be what caused SimulaQron tests to come to produce segfaults that I could not reproduce on my local system. Testing SimulaQron as far as I could in the Qrack stack on my local machine, (we're trying to support second-order dependency of it on Qrack, that is, via ProjectQ,) I detect no particular problems with Qrack as the simulator. However, depending on method of installation, SimulaQron's documentation …

CI Python version update (and README changes)

---

.travis.yml
CMakeLists.txt
include/common/parallel_for.hpp
include/qinterface.hpp
include/statevector.hpp
src/qinterface/arithmetic.cpp
test/tests.cpp

As the title says, the "atomic" library is not needed for Windows builds.

MSVC does not need "atomic" library

---

.travis.yml
include/qengine_opencl.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/pinvoke_api.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qunit.cpp
src/qunitmulti.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.cpp

This branch attempts to add support for multiple OpenCL devices in the same simulation, using a previous experimental `QInterface` design that divvies Schmidt-decomposition-separable subsystems of `QUnit` to different OpenCL devices, potentially even heterogeneous devices.

QUnitMulti (experimental feature)

---

include/qengine_opencl.hpp
src/qengine/opencl.cpp

QUnitMulti has given me a reason to look at the OpenCL code, again. This should fix edge cases for using a host pointer vs. device RAM.

Debugging SetDevice()

---

.travis.yml
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qfusion.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp
src/qunitmulti.cpp

This PR makes QEngineOCL::Compose semi-asynchronous, but it also fixes a longstanding bug in the same method: when composed QEngine instances are from different OpenCL contexts, it is not safe to use the same host pointer for two different buffers at once, even if one buffer is mapped and otherwise not used until the other is freed.

OpenCL Optimization and debugging

---

include/qunit.hpp
src/qunit.cpp

QUnit can further optimize its controlled gate buffers, if they're cleared in anticipation of an immediately subsequent measurement: controlled phase gates with both ends within the measured qubit set will not change probability amplitude norms, and measurement will destroy phase information, so these buffer cases can safely be "dumped" without application on measurement.
Also, if a QUnit sub-unit is measured across its entire length, we only need a `bitCapInt` result without a "collapse" of the sub-unit, since it will be replaced by re-initialized single qubit separable shards.

Measurement optimization

---

include/qengine.hpp
include/qfusion.hpp
include/qinterface.hpp
include/qunit.hpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qfusion.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp

The no-application-measurement in QUnit actually caused performance regression, as originally implemented, but the same principle will be an improvement if the original `ForceMReg()` methods are used, simply without applying unitarity breaking within them. This also makes for a useful "pseudo-quantum" operation mode, for the semi-protected `ForceM()`/`ForceMReg()` API in general.

Various optimization

---

examples/pearson32.cpp
include/statevector.hpp
src/qengine/state.cpp
src/qunit.cpp

For sparse-QEngine-based QUnit instances, the default implementation of `QInterface::ForceMReg()` is much faster than the standard optimized QUnit variant. This makes a proof-of-concept of hashing techniques practically viable.

Optimizing sparse QUnit measurement

---

include/statevector.hpp

Small amplitude flooring is controlled by the normalization options on a QEngine, and this happens in the body of a `par_for` loop or a kernel. Sparse state vectors should not duplicate this behavior, particularly without respecting the option to turn it off. (It's redundant, if the option to enforce it is on.)

Bug fix: don't floor in sparse state vector

---

include/common/oclengine.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/common/oclengine.cpp
src/qengine/opencl.cpp
src/qunit.cpp
src/qunitmulti.cpp

`OCLEngine` previously kept a single `std::mutex` for locking a device between setting kernel arguments and enqueuing a kernel: the mutex only needs to lock per kernel, not per device, and this was always the original intent for the `OCLEngine` system, which we missed the target on. This has been fixed. Some extraneous lock guards could also be removed, in the process.
With the locking corrected, and with attention paid to the threading limitations of STL containers, `QUnit` can now carry out parallel piece-wise `Compose()` and `ForceMReg()` calls, within its own internals. This might also benefit `QUnitMulti` performance.

Asynchronous OpenCL cleanup

---

include/qunit.hpp
src/qengine/qengine.cpp
src/qunit.cpp
test/tests.cpp

`test_fulladd_noncoding` was failing intermittently due to reliance on `ApproxCompare`, which was overkill and designer to err on the side of false negatives.
`QUnit::DECBCDC` no longer intermittently fails once `CollapseCarry()` is removed from QUnit. This method is obsolete, probably never gave a significant performance increase, and was apparently bugged.

Fixing intermittent unit failures

---

include/qunit.hpp
include/qunitmulti.hpp
src/qunit.cpp
src/qunitmulti.cpp

The previous PR seems to have exposed a bug in QUnitMulit's GetQuantumState()/GetProbs(). This drew my attention to a typing problem in QUnit's Clone(). The current fix might not be perfectly optimal, but it works, and we have always discouraged users from relying on GetQuantumState() and GetProbs() in favor of methods more realistic to a hardware quantum computer.

Debugging QUnitMulti GetQuantumState and GetProbs

---

include/qunit.hpp
src/qunit.cpp
test/tests.cpp

If the input register is entirely in the separable |+> state, Hash, INC, and DEC can be completely skipped.

Optimizing QUnit Hash/INC/DEC

---

examples/pearson32.cpp
include/common/parallel_for.hpp
include/common/qrack_types.hpp
include/qengine_cpu.hpp
include/statevector.hpp
src/common/parallel_for.cpp
src/qengine/arithmetic.cpp
src/qengine/gates.cpp
src/qengine/state.cpp

The sparse state vector option for `QEngineCPU` (when used with the `QUnit` layer) could be become an important workhorse for particular applications that cannot be handled by `QUnit` optimizations alone.
If a method acts "out-of-place," reading from the old state vector while writing into a new one, the mutex locks can be removed for reading from the old state vector. Also, as `read()` and `write()` should be basically "micro" inline methods carried out many times in a gate, every bit of performance we can squeeze out of their general implementations helps.

Sparse state vector optimization

---

src/qengine/state.cpp

As probability-checking methods do not write to the state vector at all, they are safe for concurrent reads on sparse state vectors, (even though they are not "out-of-place" operations).

Remove sparse state vector read() locks on probability check methods

---

src/qengine/qengine.cpp
src/qunit.cpp
test/benchmarks.cpp

If a system is using `RDRAND` for Qrack's random number generator, (which is the default option and ostensibly ubiquitous,) use of the opcode comes with a relatively high premium entropy rate of the random number generator. If we measure a |0>/|1> eigenstate, we don't need random data at all.
I'm also hacking away at the performance on the universal circuit benchmarks. I've added a couple of new benchmarks representative of different universal gate sets, (from [https://inst.eecs.berkeley.edu/~cs191/fa07/lectures/lecture9_fa07.pdf](https://inst.eecs.berkeley.edu/~cs191/fa07/lectures/lecture9_fa07.pdf)). In looking for potential improvements in these sets, I realized that CNOT and CCNOT with targets that are exactly |+> can be entirely skipped. This is a situation that likely comes up …

Measurement and CNOT optimization

---

test/benchmarks.cpp

This PR adds a cross entropy benchmark that can establish the accordance of results of `QEngine` types with `QUnit` types. (For the moment, parameters need to be adjusted by hand in code, to experiment.) I argue the default parameters give a reasonable experiment, and typical output looks like this:
```
$ ./benchmarks --proc-opencl-single --layer-qunit-qfusion --enable-normalization test_universal_circuit_digital_cross_entropy
Random Seed: 1587426549 (Overridden by hardware generation!)
############ QUnit -> QFusion -> OpenCL ############
Device #0, Loaded binary from: /home/iamu/.qrack/qrack_ocl_dev_0.ir
Device #1, Loaded binary from: /home/iamu/.qrack/qrack_ocl_dev_1.ir
Device #2, Loaded binary from: /home/iamu/.qrack/qrack_ocl_dev_2.ir
Default platform: NVIDIA CUDA
Default device: …
```

Cross entropy benchmark for test_universal_circuit_digital

---

include/qunit.hpp
src/common/qheader_float.cl
src/qunit.cpp
test/benchmarks.cpp

The cross entropy benchmarks on random universal circuits revealed some very well-hidden bugs in QUnit. CZ and Swap caused cross entropy test failures, but a sample of about 100 runs or more no longer shows any unexpected differences from QEngine types.

WIP: QUnit Cleanup

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

It seems that an edge case in CNOT was responsible for the very infrequent cross entropy benchmark failures.

Cross entropy debugging (CNOT edge case and TryCnotOptimize refactor)

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

In refactoring CCNOT, I accidentally removed the section where "shards" are marked "dirty" afterward.

Dirty bits after CCNOT

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

Now that we have some form of cross entropy testing between the simulator types, optimization and bug fixes will follow, as we try to bring cross entropy results fully into line, on top of unit tests.
For QUnit, it makes sense to pull cached shard amplitude checks for exact 0/1 equality into a macro, so a float rounding neighborhood can be inserted or removed as necessary and convenient.
C++ `shared_ptr` instances holding `QInterface` instances don't always seem to know when to release their garbage, during benchmarks, so we can call `reset()` when we know we're done with them.

QUnit refactor; benchmark garbage collection

---

include/qunit.hpp
src/qunit.cpp

It makes no sense to "TryCommute" on a shard that can't do anything about blocking gates, while other gates could commute. These protected methods on `QEngineShard()` have been turned into protected methods on `QUnit` instead, so that _only_ gates without optimized commutation rules can be flushed. Further, to help avoid float rounding error, `angle0` and `angle1` in `PhaseShard` instances have been modified to store their radian values _divided_ _by_ _pi_. The result is a `CZ()` gate, for example, stores a whole number, and `S()` `T()` gates differ in 1 or 2 bits of accuracy or precision, which should help make the `PhaseShard` instances more robust for exact equality checks.
Before this PR is done, the entire controlled gate buffering system will be refactored. For the time being, …

WIP: Optimization and debugging

---

include/qengine_opencl.hpp
src/qengine/opencl.cpp
src/qunit.cpp

It doesn't make any sense to try optimize by checking single bit gates for eigenstates, (they would already be cached as shard amplitudes, redundantly,) or if `ApplyEitherControlled()` would find the same eigenstates anyway in the directly subsequent course of program flow.
If the QEngineOCL destructor is called, there's no point in finishing the asynchronous queue beyond the current item on the queue.

Removing redundant optimization case checks; QEngineOCL::clDump()

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

These are small maintenance tweaks. Consistent with the general convention of QUnit, controlled gate buffer optimizations should switch between relying on exact equality or rounding based on whether the "normalization" options is on. In CNOT, if the target bit is in the |-> state, then the gate can be optimized as equivalent to a Z() on the control. When QUnit implicitly dumps its shared_ptr instances for "shards," it's better to explicitly `Dump()` them.

Optimization

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

For a reason that isn't clear to me, QUnit::CommutePhase() seems to have incorrect edge cases. It will be replaced, but, pending refactor, I'm removing it, as speed doesn't matter if logic is wrong.

Remove QUnit::CommutePhase

---

src/qunit.cpp

The bit amplitude cache always needs to be made totally "dirty" when it goes to a gate partially dirty.

MakeDirty() on X/Z, (and divert ApplySinglePhase to Z when appropriate)

---

CMakeLists.txt
include/qunit.hpp
include/qunitmulti.hpp
src/qengine/opencl.cpp
src/qunitmulti.cpp
test/benchmarks.cpp

Recent updates broke Windows and Apple build support. We seem to have fixed Windows builds last night, but this fixes Apple builds. Also, it's better to check the context ID we set up in `OCLEngine` for whether buffers can be reused or shared, rather than the Windows kludge we put in last night.

Fix Apple build support

---

src/qengine/opencl.cpp

Since QEngineOCL::Clone() will always produce a new instance using the same OpenCL device, it will always share the original context, and it can be copied simple with an OpenCL buffer copy operations.

QEngineOCL::Clone() optimization

---

.travis.yml

Qiskit released a tag at pretty much the same moment as us, and their CI build is broken. (Of course!) I believe the just-previous release should be fine, for now.

Fix Qiskit version in CI

---

src/qunit.cpp

Theoretically, controlled phase gates alone cannot change the |0>/|1> basis probability of a qubit. This qubit with buffered controlled phase gates could act as the control of a subsequent gate, in which case optimizations based on |0>/|1> eigenstates can be accounted without flushing buffered phase gates. Other optimizations follow similarly from the hypothetical assumption of |0>/|1> basis probability invariance under additional controlled phase gates, only.
The above hypothesis has been tested with the random universal circuit cross entropy unit tests, and they pass consistently.

Phase optimizations

---

include/qunit.hpp
src/qunit.cpp
test/tests.cpp

It seemed like the optimizations of #333 could easily be extended to `SWAP` variants, but I hesitated to try this for worry over invalidating the "quantum supremacy" benchmark, without sufficient tests. Herein, we add a cross entropy unit test of the "quantum supremacy" test, so we can keep tabs on whether optimizations change those measurement distribution outcomes, (which they should never do). (Additionally, one can switch `SWAP` variants into the more general `test_universal_circuit_digital_cross_entropy`, which I have also tried.)
It looks like we're all good. This is also a modular test of the cross entropy of `QUnit` against `QEngine` for the "quantum supremacy" circuits in general. It's not necessarily granted that width and depth will scale for a hardware test, but I think it's …

Swap variant optimizations; "quantum supremacy" cross entropy unit test

---

src/qunit.cpp

H gate buffers will ultimately be flushed anyway, if swap variant optimization checks fail, so it makes sense to flush them 1) before the "shards" become more entangled due to flushed controlled phase gate buffers and 2) when they have some chance of triggering an optimized case check.

Flush H buffers before swap variant optimization checks

---

include/qinterface.hpp
include/qunit.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/benchmarks.cpp

It's become cumbersome not to have `CCZ` as a primitive. Also, a benchmark has been added based on the { H, Z, CZ, CCZ } set, (which I believe is universal).

Add CCZ API

---

include/qunit.hpp
src/qunit.cpp

While the random universal circuit benchmark happened to be running correctly as exactly defined, there was a bug in the handling of "inversion" buffers, which that benchmark could never trip. Since this affects general correctness, we'll be iterating to release 5.1 with this, after due scrutiny.

Debugging buffered "inversion" gates

---

src/qunit.cpp
test/tests.cpp

As in all cases where "inversion" buffers are flushed, `Swap` can potentially avoid applying cached phase gates. Also, as I was debugging with it over the weekend, I have added an "identity gate" option to one of the cross entropy tests, which makes it cover a much more general set of circuits.
I believe we're tagging this as v5.1, when this is merged, due to the bug fix in `Swap`.

SWAP() buffer dumps; add "identity gate" option to cross entropy test

---

include/qunit.hpp
src/qunit.cpp

Now that the bug in Swap() has been fixed, many buffer commutation rules I expected to work, but had kludged over to cover the cross entropy failures, have started to work as expected.

Ease buffer commutation restrictions, subsequent to Swap() bug fix

---

src/qunit.cpp

`isOpposite` in `CommuteH()` was likely missing optimization opportunities, due to a bug. This bug was unlikely to lead calculation errors, commonly or ever.

CommuteH() isOpposite bug fix

---

include/qunit.hpp
src/qunit.cpp

Per issue #342, "anti-controlled" buffers have been added to QUnit. This allows for full commutation between "inversion" gates (like `X`) and QUnit controlled phase buffers. The full ramifications for optimization have not been fleshed out, but the backbone of the new functionality and the library in general is working and passing cross entropy benchmarks and unit tests.

Issue 342 - "Anti-controlled" buffers

---

include/qunit.hpp
src/qunit.cpp
test/tests.cpp

I cut a dead macro from QUnit, encapsulated eigenstate buffer flushes in inline methods, and removed CheckShardSeparable() from all places except ProbBase(), which is currently the only place where it can make a difference. I believe the series of CI failures is due to putting in a buffer commutation optimization attempt first thing in the branch, then never noticing it was repeatedly failing CI, but we'll see when the last commit clears.

QUnit refactor

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.cpp

The controlled gate buffer code wasn't actually using most of its intended capabilities, but the commutation rules planned were luckily on fairly solid footing. Now, CZ/CNOT commutation and "anti-controlled" buffers are actually utilized in this code, as originally intended. Eased restrictions on commutation relations for buffers will hopefully follow soon.

Debugging CZ/CNOT buffer commutation and anti-controlled buffers

---

.travis.yml
src/qunit.cpp
test/tests.cpp

In total across all QUnit sub-types, this branch just passed at least 36 rounds x200 trials apiece of cross entropy benchmarks at the old level of stringency. (I upped it in the branch merged earlier today in order to more quickly and consistently track down failures, without running many repeated tests.) I'm leaning towards attributing the intermittent failures on the new, much more stringent tests to "statistics." Rather, there _is_ a significant divergence between QUnit and QEngine by significant _width_ and _depth_ at relatively fractional edge cases, not attributable to uncompounded rounding or ideal statistics of sample, for the precision of Qrack and most quantum simulators. However, I'm thinking these are the intended _features_ of QUnit manifesting on very small fractional …

Reverting cross entropy unit test stringency

---

src/qunit.cpp

Only certain controlled inversion cases need to be flushed, when a controlled phase gate is applied to arbitrary bits. Also, controlled phase gates with same two phase factor arguments are equivalent to a phase gate without a control bit.

Better commutation (and small memory leak fix)

---

include/qinterface.hpp
include/qunit.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/tests.cpp

We're expanding stack support, again. XACC has some demand for a controlled `H` gate. As can be seen in this diff, it's trivial to add this gate. `QUnit` can immediately optimize it, at least to first pass, so I'd like this in the public API, rather than implemented via decomposition.

Optimized controlled-H gate for XACC interface

---

src/qunit.cpp

While testing Qrack with the VQE in the XACC plugin under development, we weren't reaching the ground state of deuterium H3, (if I understand the point of the test case). This appears to have been due to a bug in single qubit phase gate commutation, implicating commuting "inversion" targets while being in |+>/|-> basis at the same time.

VQE debugging

---

include/qengine.hpp
include/qinterface.hpp
include/qunit.hpp
src/qengine/qengine.cpp
src/qinterface/qinterface.cpp
src/qunit.cpp
test/tests.cpp

The "fSim" gate is useful in the simulation of quantum particles with fermionic statistics. XACC natively supports it, and I would like to take its implementation behind Qrack's public API layer. (I have made a substantial first pass at QUnit optimization, for it.)

Adding "fSim" gate

---

src/qunit.cpp

It occurred to after 1e0dfd2 that the `CommutePhase()` call in `ApplySingleInversion()` probably needed the same fix; commuting phase effects with inversion targets requires first transforming out of |+>/|-> basis to |0>/|1> basis. (It's not immediately obvious to me why this shouldn't work in |+>/|-> basis, but it seems it doesn't.) I'm testing this further, now.

Analagous fix for inversions, as 1e0dfd2

---

cmake/Format.cmake
include/qunit.hpp
src/common/parallel_for.cpp
src/qengine/arithmetic.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qunit.cpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.cpp

I identified and fixed a bug, per #357, caused by commuting an inversion gate with opposite phase angles around an `H` gate. This is probably the least well-behaved of the cases that commute at all, (basically 4 cases of single-parameter families in total,) although it's not clear to me why this fails. To first consideration, there's no problem with the commutation itself, but maybe this causes something disallowed to happen downstream, with other commutativity considerations. I'll poke at it for a few minutes, and I'll see if I can restore the case under other conditions.

Issue #357: Fixing CommuteH() bug

---

include/qunit.hpp
src/qunit.cpp
test/tests.cpp

In the case that the optimization to compose inversions with phase buffers actually hits, it seems that it fails. (It's tricky to actually trigger this case.) This optimization attempt has been removed.

QUnit buffer debug

---

src/qunit.cpp
test/benchmarks.cpp

Swap gate variants lost some presumed efficiency, not long ago, to fix their general correctness. They are good targets for attempting optimization, again, under the suite of tests by which they were originally debugged.

Optimizing QUnit::Swap variants

---

src/qengine/opencl.cpp
test/benchmarks.cpp

QBCAPPOW should accept an (almost) arbitrarily high "n," where the number of qubits is 2^n, so long as the user does not cause over-allocation due to representational entanglement in QUnit. A type safety bug broke this feature.

Fix QBCAPPOW; add test_qft_cosmology_inverse

---

cmake/RDRand.cmake
examples/teleport.cpp
include/common/rdrandwrapper.hpp
include/qinterface.hpp
src/common/rdrandwrapper.cpp
test/benchmarks.cpp

I've thought for a long time that it might be good to have a standard way of loading RNG data from arbitrary system sources, (like Linux' `/dev/random`). A good first pass at a very generic approach is to load binary random number data files from disk. I didn't expect this to be an officially demanded and supported option, but it turns out, if RNG is offloaded to disk I/O, there is a _huge_ speed increase on the QFT, for example, seemingly in excess of maybe an 85% reduction in total execution time by high qubit counts. The feature isn't perfect, but I'll merge this when it's to my standard.

Option to load random number files from disk

---

.travis.yml
include/qunit.hpp
src/qunit.cpp
test/tests.cpp

So long as an invert control buffer is not acted on as a target at the same time, it can commute as the control bit of any number of invert and phase buffers at once.

Buffer controls can control inverts and phase at once

---

.travis.yml
src/qunit.cpp

Because of the reliance on `QUnit` public API methods, given the original state of the `Swap()` method without `TransformBasis1Qb()` calls, it does not seem to be necessary to always first make these calls in swap method variants.

Swap variants: remove TransformBasis1Qb() calls

---

include/qunit.hpp

Certain restrictions on `OptimizeBuffer()` were either never necessary or are no longer necessary as kludges. These changes theoretically increase the optimization gains of calls to `OptimizeBuffer()`.

Loosen restrictions on OptimizeBuffer()

---

src/qunit.cpp
test/tests.cpp

Certain commutation restrictions put in place along the way to a general pass on random universal circuit cross entropy tests can be backed off, as kludges which are no longer necessary.

WIP: Remove unnecessary commutation restrictions

---

src/qunit.cpp

Since control/target designation is ambiguous for controlled phase gates that only impart phase when both "control" and "target" are true, and since inversion commutation restrictions were already relaxed with controlled phase gates, I tested this for 2400 iterations of random universal circuit cross entropy at depth of 5, and it looks like commutation restrictions can be further relaxed.

Relax commutation rules on phase buffers

---

include/qunit.hpp
src/qunit.cpp

Because of the current inability to compose phase buffers with inversion buffers, it seems like some commutativity could be saved by directly buffering inversion gates, instead of composing them from H, CZ, H patterns.

Directly "AddInversionAngles()" for CNOT

---

CMakeLists.txt
src/qunit.cpp

The recent changes in CNOT/AntiCNOT hurt performance and are reverted here, though I consistently find myself reaching back for AddInversionAngles(), which has been verified in its current form. Also, it is often efficient to flush certain "isSame" phase gates on commutation with H.

Flush buffers when efficient; better default PSTRIDE setting

---

.travis.yml

In the Qrack/Qiskit plugin repository, I replaced the unit tests with the subset of the new IBM tests that we currently support. Basically, we support almost everything except noise, snapshots, and certain custom unitary gate operations. Qiskit has also improved their case coverage for sampling optimizations, and replicating this behavior in the Qrack plugin is on my list, but it's not top priority because the new cases seem to be entirely covered by exactly equivalent rearrangement of instructions in the circuits it covers, (i.e. "It's the optimizing compiler's job," or the programmers').

CI update (Qiskit)

---

examples/qneuron_classification.cpp

QNeuron layer controls in the example were accidentally identical for all QNeurons with the same number of controls. This has been fixed.

Fixing QNeuron layer controls

---

examples/qneuron_classification.cpp

This doesn't affect the example as exactly written, but I confused a conceptual `bitCapInt` for a `bitLenInt`. This is important if the example is adapted, such as to include more than 255 neurons.

bitLenInt/bitCapInt bug in QNeuron classification example

---

src/qunit.cpp

I've tested another couple of relaxations of commutation restrictions, in QUnit.

Improved commutation of phase/inversion buffers

---

src/qunit.cpp

It's preferable, if flushing an H gate can prevent the application of a 2-qubit gate.

Flush H on target to compose phase/invert buffers

---

include/qunit.hpp
src/qunit.cpp

While we definitely see some significant general improvements from controlled phase/inversion buffers, the number of possible simultaneous buffers is proportional to the power set of qubits in the QInterface. Therefore, when working close to capacity, there is basically _no_ improvement in "big-O" from buffering. However, we can try to stay as low below buffering capacity as possible by flushing "efficient" gate instances at every reasonable opportunity. One such opportunity is when controlled phase buffers have two identical phase factor arguments, which can be applied as a single qubit phase gate instead, leveraged here.
Also, `isOpposite` optimization for inversion buffers was not previously allowed, in `CommuteH()`. I relaxed this restriction, previously, only because the edge case …

Flush phase buffers when efficient (and fix CommuteH isOpposite bug)

---

src/qengine/opencl.cpp

The acquisition of a Turing architecture NVIDIA card has given me reason to revisit OpenCL work group sizing parameters. Honestly, after reading more guidelines for OpenCL (and CUDA) group sizing based on "warp" SIMD, it's obvious I didn't completely understand `QEngineOCL` group sizing for efficient use of more general architectures.
My primary GPU test case has been the (mobile) GTX 1070, for over a year. The 1070 architecture happens to be very "square" for purpose of quantum computer simulation. (By the way, I think it happens to still be an excellent value buy for Qrack, at the moment.) The RTX 2070 Turing architecture is "lopsided," but this branch returns a small gain on it, over my original 1070 benchmarks, with just a tiny tweak in work group sizing.
I'd even guess that this …

Optimizing OCL work group sizing (tested on NVIDIA Turing)

---

src/common/qengine.cl
src/common/qheader32.cl
src/common/qheader_double.cl
src/common/qheader_float.cl
test/tests.cpp

The alternative CUDA implementation has helped me identify some unused variables in the OpenCL kernels, and I have run `clang-format` on the file. On my new development machine, it seems like a bug has become apparent in OpenCL `Decompose`, and I'll add a fix for that, here, as well.

OpenCL cleanup

---

src/qengine/opencl.cpp

It never should have been necessary to clear `nrmBuffer` in `QEngineOCL` before using it, but it seemed to be, at one point. I suspect that some instance of summation of results in that buffer iterated over the entire buffer instead of the expected working portion of it for its particular kernel. I checked all instances where the buffer is summed over, and the bounds all seem to be correct.
In any case, there no longer seems to be any problem with removing these lines, which were likely always a kludge.

Removing old OCL kludge

---

src/common/oclengine.cpp
src/qengine/opencl.cpp

(You learn something new every day:) Apparently, buffer migration is implicit in OpenCL, when a memory object is used in a different queue/device context. There are APIs which can explicitly handle the migration ahead of time, so that the cost doesn't hit at the point one tries to write to the buffer, but it doesn't seem like we need them. While this might be "6 and half a dozen" compared to our manual handling for platform switching, the OpenCL API is probably better at this under-the-hood than we are, and we might as well save the code complexity.

Implicit OpenCL buffer migration; default device env. var.

---

src/qunit.cpp

I introduced a bug in `ApplyAntiControlledSingleBit()`, the other day. `find()` algorithm results checked against the wrong list.

Fix bug in ApplyAntiControlledSingleBit()

---

include/common/oclengine.hpp
src/qpager.cpp
test/benchmarks.cpp

The `QUnit` with `QPager` benchmarks seem not actually to have dispatched to the intended `QInterface` type. Also, since the single-qubit-gate kernel operates on amplitudes pairwise, per instance, there should be at least an additional factor of 2 on the preferred OpenCL paging size, just to first consideration. Further, the "preferred concurrency" of the OpenCL device shouldn't necessarily have anything to do with powers-of-2 clamping preferred for state vectors, so I have simplified the relevant method in the OCLEngine system.

Fixing QPager benchmarks and automatic paging limits

---

include/qpager.hpp
src/qpager.cpp

QPager lambda expressions should capture at least their loop control variables by value, so that the value does not change during thread execution. Also, this branch adds an optimization for single-qubit phase/inversion gates in QPager.

Debug QPager lambda closures; QPager::ApplySingleEither()

---

include/qpager.hpp
src/qpager.cpp

Phase and inversion gates can be significantly optimized, under the general strategy of "paging." This PR adds such support for controlled gates.
"Meta-controlled" gates benefit from this, (where the target bit is at inter-page level, rather than intra-page). "Semi-meta-controlled" gates, by the naming convention of `QPager`, (with the opposite case for target bit, intra-page rather than inter-page,) seem to be equivalent in this special case to the already-implemented general gate case.

QPager controlled phase/invert optimization

---

include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qpager.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp
src/qunit.cpp
src/qunitmulti.cpp

QPager can theoretically handle multi-accelerator execution without any particularly complicated modification or configuration. A list of OpenCL device IDs are passed in and, simply, as "pages" are indexed, they are assigned device IDs from this list by ascending modulo repetition. In other words, from 0 page index to highest, device IDs are also assigned from the device list index 0 to highest, repeating the device list as many (full or partial) times as necessary to cover all pages.
Because QPager probably works best initialized with a paging qubit threshold, as it already is, rather than an absolute count of pages, there seems to be no particular complication to this system from `Compose()`, `Decompose()`, or `Dispose()`. Assuming random access of qubits with no particularly preferred …

Accept device list argument for QPager multi-accelerator

---

CMakeLists.txt
include/qengine_opencl.hpp

The `ZeroAmplitudes()` method is better implemented than the original `QEngineOCL` destructor, and it serves the same function.

Simplify and correct ~QEngineOCL()

---

cmake/OpenCL.cmake

CMake informational messages have been brought into line with the ENABLE_SNUCL option.

Print SnuCL CMake info

---

include/qengine_opencl.hpp
src/qengine/opencl.cpp
test/tests.cpp

For a cluster environment, OpenCL "host pointers" (general RAM heap allocation for accelerator device operations) might not be supported at all, or otherwise come at a very high premium in a very limited specific resource pool. However, more generally, use of general heap might give no advantage if it can be totally avoided, except in very specific cases. To a certain extent, transparency of the OpenCL API efficiently and simply manages cases where switching to host pointers becomes necessary, if they are even available in the environment and for the device. Sometimes, (or frequently,) host pointer addressing requires transparent device memory "pinning," anyway, in which case redundancy with device RAM is not even truly avoided, (though my experience is that CPUs directly address general …

Don't use (OpenCL) host pointer for nrmBuffer

---

test/benchmarks_main.cpp
test/test_main.cpp

QPager is still unstable, so I am disabling its unit tests and benchmarks by default, so as not to impede existing default test/benchmarks commands. By explicitly selecting QPager through command line options, its tests and benchmarks can still be run.

Temporarily disable default QPager tests/benchmarks

---

src/qengine/opencl.cpp

SnuCL does not support the use of OpenCL host pointers for buffers, (understandably,) but this is also a point of general good OpenCL practice, in most cases. All references usage of host pointers for OpenCL buffers has been removed in `QEngineOCL`, except for in `LockSync()`. Unnecessary references to `LockSync()` have been removed. Remaining reference to `LockSync()` is avoided if the `ENABLE_SNUCL` macro is true.

Remove OpenCL host pointer instances

---

src/qengine/opencl.cpp
test/benchmarks.cpp

C++ `std::chrono` seems to be a much better chronometer API for our purposes than (I think, C) `clock`. Benchmarks, so far, appear to return numerical timings that are approximately the same or faster, depending upon previous use case. (I tested `test_qft_cosmology` and `test_universal_circuit_digital`.)

Use different (C++) clock for benchmarks

---

src/qengine/opencl.cpp

This removes more usages of OpenCL host pointers. Besides specifically intended cases, dependent on certain API method usages, I think this removes all undesirable host pointer usage. I expect no change in performance, worst case, or a significant performance improvement in certain API methods, best case.

Remove usages of OpenCL host pointers

---

src/qengine/opencl.cpp

In the last PR, I neglected to remove unnecessary default wait events from the OpenCL queue. This probably makes no effective difference, but it's more correct.

Remove extraneous emplace for wait events

---

include/qengine_opencl.hpp
src/qengine/opencl.cpp

The `LockSync()` and `UnlockSync()` protected methods of `QEngineOCL`, while potentially useful, are currently used nowhere, since they are sub-optimal if they can be avoided. Here, the unused methods are removed.

Remove unused methods from QEngineOCL

---

.travis.yml
src/qunitmulti.cpp

It looks like `matplotlib` used in ProjectQ needs an update, due a deprecation warning. I need to temporarily disable the ProjectQ tests, as a result.
Also, while I am debugging third party unit tests, I'm trying to improve overall external stack integration. Toward this end, it now makes practical sense to expose `QUnitMulti` to other libraries, and it makes further sense to use the `deviceID` parameter for OpenCL as an override for the _default_ device ID, for the purposes of `QUnitMulti`.

Unit test fix

---

include/qpager.hpp
src/qpager.cpp
test/tests.cpp

This PR optimizes SWAP variants in QPager.
Personal note: hurricane Isaias totally knocked out my power and internet. I have a generator, and I tweaked this PR together without internet last night for lack of anything better to do, but most of our town might be without utilities for days. (I put these commits in through the GitHub web interface, but I can't even tether.) Work on Qrack will likely be slow to nil, until we're restored.

QPager swap optimization

---

src/qpager.cpp
test/tests.cpp

I fixed a small bug in `QPager::Swap` variants, after fixing a more significant bug in `CSwap`'s unit test.
Also, I drafted almost a complete `QPager::ZeroPhaseFlip` optimized implementation, which has been disabled until I can finish debugging it, tomorrow.

Debugging QPager Swap variants (and drafting ZeroPhaseFlip)

---

src/qpager.cpp
test/tests.cpp

This activates and debugs the optimized version of `QPager::ZeroPhaseFlip()` that I merged last night.

Optimized QPager:ZeroPhaseFlip()

---

include/qpager.hpp
src/qpager.cpp

Most "meta-" variants of `Swap` in `QPager` were half-baked, but this only became apparent once full unit tests were feasible. Temporarily, most of these variants have been removed. (This doesn't affect the public API, just the implementation "under-the-hood.")
Two different models of NVIDIA graphics cards seem to give peak `QPager` performance for their "preferred concurrency" qubits, +12 qubits. I only have two points to plot my line, but users can test for themselves in the benchmarks, particularly `test_x_all`, in this case.
More "lazy separation" optimizations have been followed-through on.

QPager Swap debugging, and optimization

---

src/qpager.cpp

"Lazy separation" can be carried further, in `QPager::Swap` variants.

Debugging/optimizing QPager::Swap variants

---

include/common/oclengine.hpp
include/qengine_opencl.hpp
include/qfactory.hpp
include/qinterface.hpp
include/qpager.hpp
include/qunitmulti.hpp
src/common/oclengine.cpp
src/qengine/opencl.cpp
src/qpager.cpp
src/qunitmulti.cpp
test/benchmarks_main.cpp
test/test_main.cpp

I apologize for this, but, weirdly enough, `QUnitMulti` wasn't engaged at all in `qfactory.cpp` and therefore also not in unit tests or benchmarks. (Some unspecified configuration of `QUnit` was being used, instead.) When I re-engaged `QUnitMulti` in the factory, I also debugged it. This should be fully compatible with OpenCL v1.1 and SnuCL, (and non-trivially so, now).

QUnitMulti debug

---

src/qengine/opencl.cpp
src/qpager.cpp

When amplitudes are zeroed throughout an entire `QEngine` because it is a part of a `QPager`, `ResetWaitEvents()` also fails. Skip it, if the `QEngine` is zeroed.

Fix QUnit->QPager benchmarks

---

include/common/oclengine.hpp
src/qengine/opencl.cpp

I hadn't appreciated that `QPager` layered over `QEngineOCL` makes for a situation where multiple `QEngineOCL` instances share a device/platform context. It was always part of the design intention that `QEngineOCL` should work in at least certain multi-threaded situations, but we didn't have a great opportunity to test this until `QPager`. It seems that some of the most immediate bugs are due to `DispatchQueue()` without a mutex on wait event lists, but this is hopefully fixed, now.

Lock wait events queue on dispatch for all QEngineOCL instances

---

src/qpager.cpp

The "deviceID" parameter in QPager now selects the default device.

QPager device ID default

---

include/qengine_cpu.hpp
include/qpager.hpp
src/qpager.cpp
test/tests.cpp

This optimizes `QPager::Swap()` with one bit "meta-" and one bit within "pages."

QPager::SemiMetaSwap()

---

CMakeLists.txt
include/common/config.h.in
include/common/parallel_for.hpp
src/common/parallel_for.cpp
src/qengine/state.cpp

I find that I am using `QEngineCPU` in important cases, so it's due for a round of optimization. We never considered performance on this engine type to be particularly important, in expectation of OpenCL being available even for CPU-only systems, but I'm very glad we maintained a pure C++11 implementation, in retrospect. The `QEngineCPU::Apply2x2()` code becomes slightly unwieldy, but it's important to branch outside of its lambda expression kernel, so the complexity is acceptable, with a payoff.

QEngineCPU optimization

---

include/pinvoke_api.hpp
include/qengine_cpu.hpp
include/qinterface.hpp
include/qpager.hpp
include/qunit.hpp
src/pinvoke_api.cpp
src/qengine/state.cpp
src/qunit.cpp
test/tests.cpp

In this branch, user code has a method to set QEngineCPU thread concurrency, (and QUnit shard concurrency, layered on top of QEngineCPU,) including in the PInvoke API.

QInterface::SetConcurrency()

---

CMakeLists.txt
include/common/dispatchqueue.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/common/dispatchqueue.cpp
src/qengine/state.cpp
src/qunit.cpp
src/qunitmulti.cpp

In this branch, QUnit now waits to initialize QEngine instances until they cannot be "emulated" via single bits. In many cases, this reduces and defers threading and OpenCL buffer costs.

Lazy QEngine initialization in QUnit

---

.travis.yml
cmake/QUnit_CPU_Parallel.cmake

Feature #456, implemented by #457, makes it so that asynchronous CPU dispatch simply "just works" as far as stack integration is concerned. We can (and should) leave the option in CMake to turn it off, but the default can be "ON," and unit tests should run with the default "ON" option.

Default -DENABLE_QUNIT_CPU_PARALLEL=ON

---

src/qunit.cpp

I missed restoring section of optimization code that I disabled in QUnit, in the last few PRs. (This is not particularly important, but it's nice to have.)

Restore disabled QUnit optimization code

---

src/qunit.cpp

This mirrors another (tiny) optimization in a similar method in QUnit.

Avoid redundant std::find

---

include/qfactory.hpp
include/qunitmulti.hpp
src/qunitmulti.cpp
test/benchmarks_main.cpp
test/test_main.cpp

If QHybrid is used for the "shard" type under QUnitMulti, not only does this allow faster operation for small counts of "shard" qubits, but the QUnitMulti switching threshold can benefit from not being taxed under the QHybrid threshold for GPU mode.

Enable QUnitMulti layering over QHybrid

---

src/qunitmulti.cpp

QUnitMulti previously had a check for device allocation limits, and it reallocated on the default device if they were exceeded by any other device. This PR restores that behavior.

Restore QUnitMulti device limit checks

---

src/qunitmulti.cpp

After the flailing on master earlier today, to meet time-sensitive priorities, this refactors that work. It should make no performance or logical difference.

Clean up QUnitMulti:EntangleInCurrentBasis()

---

src/qunit.cpp

Even in the |+>/|-> basis case, buffer control bits commute, such that the buffer flushing restrictions can be slightly relaxed.

QUnit CNOT: control bits commute

---

include/qunit.hpp
src/qunit.cpp

While the |+>/|-> basis CNOT case is great to have, I wasn't considering that reverting 2-qubit buffers could change the |+>/|-> basis in the middle of the optimized case. Also, with this fixed, we can continue to buffer H gates on "wires" that buffer phase and inversion gates at the same time. This should help with #367.

CNOT debug and optimize

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

We're not yet at full parity with stabilizer simulators, but I have added a flag to each QUnit sub-engine that keeps track of whether all flushed gates have been Clifford. This allows optimizations to calculating bit probability and separating qubit representations. The payoff is typically small-to-nil, but this forms the basis for further work toward parity with stabilizer simulators

Clifford set optimization

---

src/qunit.cpp

|0>/|1> and |+>/|-> basis eigenstates are checked together in `ProbBase()`. I'm running benchmarks and checking CI before merge.

Check for |+>/|-> basis in ProbBase()

---

include/qunit.hpp
src/qunit.cpp

In refactoring ProbBase, recently, I accidentally stopped it from recognizing separable eigenstates. (Overall, the implementation is much cleaner, now.)

QUnit::ProbBase optimize

---

src/qunit.cpp
test/tests.cpp

Based on cross entropy integration tests, it seems that QUnit::ProbBase() leads to logical errors on decomposing an X-basis eigenstate. We simply drop that decomposition, here.

QUnit::ProbBase() debug

---

include/qinterface.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
test/tests.cpp

Since QUnit fluently switches between Z and X basis, and given some experimentation with stabilizer formalism, I'm curious about Y basis optimizations, in coordination with (computational) Z and X

Simplify Z to Y basis transformation to 1 gate (and inverse)

---

include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
include/qinterface.hpp
include/qpager.hpp
include/qunit.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp
src/qunit.cpp
test/tests.cpp

Decompose() must take a destination QInterfacePtr with qubit width equal to the "length" parameter of Decompose. Since Decompose() can't accept an argument different from the size of the destination pointer, we might as well remove the length parameter and specify the "length" explicitly via the size of the passed-in QInterfacePtr.

Remove redundant 'length' param from Decompose() signature

---

src/qunit.cpp

In QUnit::Detach(), which is a protected method underneath Decompose(), the destination QInterface shards were offset out of bounds, and the shard pointer reassignment can be fixed and simplified.

Fix offset and pointer bugs in QUnit::Detach()

---

src/qunit.cpp

The update order of "isClifford" and "bit" in QUnit::EntangleInCurrentBasis() was wrong, leading to the wrong bits having their "isClifford" pointer updated

Update isClifford before 'bit'

---

src/qunit.cpp

We might be able to get more aggressive about preserving the `isClifford = true` flag in QUnit shards, but this was not the intended algorithm, and I can't guarantee general accuracy without this fix.

Sweep all shards for isClifford update after QUnit entangle

---

src/qunit.cpp

QUnit::ProbBase() also resets the remaining shard when pulling 1 qubit off a unit of 2, leaving a single remainder qubit, which can be cached. This branch optimizes that caching. (I'm pulling this work aside from `stabilizer` as independently useful.)

ProbBase: Separate remaining single shard in Z or X basis

---

include/qstabilizerhybrid.hpp

When a QStabilizerHybrid encounters a CCNOT or CCZ gate, it can sometimes handle it as a Clifford gate, borrowing an optimization method from QUnit.

CCNOT/CCZ overrides for QStabilizerHybrid

---

include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
src/qstabilizer.cpp
src/qunit.cpp

QUnit's buffering system doesn't seem to give an obvious performance advantage, at least when layered over QStabilizerHybrid. If QUnit detects that it is layered over a QStabilizerHybrid, it can skip buffering exclusively in this case.

Skip QUnit buffering, if QUnit -> QStabilizerHybrid stack

---

src/qunit.cpp
test/benchmarks_main.cpp
test/test_main.cpp

There's no obvious advantage to buffering a controlled gate in QUnit, if both control and target qubits are already entangled in the same "unit."

Skip QUnit buffering if two shards are in same unit

---

src/qstabilizer.cpp

There are cases where QStabilizer::M() works in the "scratch" row of Aaronson's tableau, to no meaningful end. We skip these cases, and we note that preparing form for `Decompose()` and `Dispose()` could depend on repeating the deterministic measurement routine to recursive exhaustion at this case.

Skip end of QStabilizer::M() if redundant

---

include/qunit.hpp
src/qunit.cpp

A stack of QUnit -> QStabilizerHybrid seems to be stable, but performance is not equivalent to the reverse layer order, with or without QUnit buffering.

Revert skipping QUnit buffer if QStabilizerHybrid shard

---

include/qinterface.hpp
include/qstabilizerhybrid.hpp
src/qstabilizerhybrid.cpp

I originally thought that QStabilizerHybrid would be similar to QHybrid, in that it would be just a wrapper, appropriate for a header-only implementation. However, there is significant original logic in QStabilizerHybrid, to graft QStabilizer to QInterface. Let's move this logic back into the *.cpp file.

Move QStabilizerHybrid logic from header into .cpp

---

src/qstabilizerhybrid.cpp
src/qunit.cpp

With this edge case covered, X basis buffering can be restored for QUnit -> QStabilizerHybrid. 2 bit buffering is still in development. Also, skip a more costly `MAll()` if not for QStabilizerHybrid shards.

Cover X basis buffer stabilizer edge case

---

src/qunit.cpp

I thought I had X basis buffering compatible between the two pieces, but that felt out of the last PR in debugging. This restores QUnit -> QStabilizerHybrid effciency on `test_stabilizer`.

Skip buffering for QUnit -> QStabilizerHybrid

---

src/qstabilizerhybrid.cpp
src/qunit.cpp

QStabilizerHybrid needs non-obvious Clifford cases diverted to function optimally with QUnit. This corrects and expands the case handling on one such compilation.

QStabilizerHybrid::ApplySingleBit() fix

---

include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
include/qinterface.hpp
include/qpager.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/qstabilizerhybrid.cpp
src/qunit.cpp

QStabilizerHybrid performs better using C++ float or double "epsilon" macros. While we have set our tolerances lower than this, it is likely the limiting systematic error in multiplying gate matrices.

REAL1_EPSILON is likely to be common limit of systematic error

---

src/qstabilizerhybrid.cpp
src/qunit.cpp

This branch restores QUnit buffering, when QStabilizeHybrid is used for the shard. One commutation rule, CommutePhase(), is suppressed in the case of QStabilizerHybrid, in order to avoid producing non-Clifford intermediate gates in the course of a purely-Clifford circuit. Most benchmarks are close to parity with QUnit -> QHybrid, but `test_qft_cosmology` actually sees a large improvement!

Restore buffering with QUnit -> QStabilizerHybrid (except CommutePhase)

---

src/qunit.cpp

Per #507, it has occurred to me that we can simply skip all cases of after-the-fact qubit separation in QUnit, only if the shard type is QStabilizerHybrid. This should stabilize the API generally, though it's still likely usually preferable to avoid `Prob()`-like methods with QStabilizerHybrid stack, from a performance standpoint.

Skip QUnit::SeparateBit() if QStabilizerHybrid shards

---

src/qunit.cpp
src/qunitmulti.cpp
test/tests.cpp

At one point, QUnitMulti needed to guarantee that sub-engine types conformed to the `QEngine` interface/sub-class. Since `QHybrid`, this is no longer the case. It doesn't make sense for QUnitMulti to use any sub-type that doesn't involve OpenCL, but it will likely break nothing, so we remove the check on sub-engine type.

No need to filter QUnitMulti sub-engine types

---

src/qstabilizer.cpp

When compiling on Windows, using `std::time()` was a compilation error. This is because `time()` is a C function.

"time()" is a C function

---

CMakeLists.txt
include/qstabilizer.hpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/catch.hpp
test/test_main.cpp
test/tests.hpp

Fully utilizing the Catch2 benchmark features might be too extensive of a change, for now. However, we apparently have demand for at least a CLI option to choose the number of samples per test, since Catch2 inserts this in its `--help` menu and does not seem to provide a configuration option to disable it. I have updated our version of the Catch2 header, disabled all unused benchmark CLI options, and basically duplicated the benchmark samples option, as it was, to actually support just this option.

Update Catch2 and provide --benchmark-samples option

---

examples/qneuron_classification.cpp
include/hamiltonian.hpp
include/qengine_cpu.hpp
include/qinterface.hpp
include/qpager.hpp
include/qstabilizer.hpp
include/statevector.hpp
src/common/parallel_for.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp

It was brought to my attention that the build option for 128+ qubit QInterface types was broken. This PR fixes compilation. Please remember, underlying "Schrödinger method" simulation types cannot handle this many qubits, but QUnit potentially can, in limited cases.

Fix 128+ qubit builds

---

include/qunit.hpp
src/pinvoke_api.cpp
src/qunit.cpp

There appears to have been an incorrectly handled single qubit edge case in QUnit::SetQuantumState(). (This does not yet fix the last two Q# simulator unit tests.)

QUnit::SetQuantumState() debug, and PInvoke DLL refactor

---

include/qunit.hpp
src/qunit.cpp

Terms were reversed in QUnit::TransformInvert(). (It's amazing how long a bug like this can go unnoticed, basically because it remains _almost_ equivalent for many observables.)

Fix flipped terms in QUnit::TransformInvert()

---

src/pinvoke_api.cpp
src/qunit.cpp

This PR addresses the single remaining Q# unit test failure. Semi-related, it also forces more exact floating point equality checks for `QUnit` buffering optimizations. Since these `QUnit` changes don't hurt performance on a benchmark like `ccz_ccx_h`, the exact checks are preferable, (and they do regularly trip their conditional optimizations, we've seen for a long time).

All Q# unit tests debugged, and QUnit precision

---

src/pinvoke_api.cpp
src/qengine/opencl.cpp
src/qunit.cpp

Controls were not correctly trimmed and entangled in the QUnit controlled variant of UniformParityRZ, but this has been fixed.

UniformParityRZ debug

---

src/qengine/opencl.cpp
src/qstabilizer.cpp
test/benchmarks_main.cpp
test/test_main.cpp

Properly, `QUnitMulti` is a "layer" interface rather than akin to an underlying `QEngine`, but the test and benchmark selection options never properly managed that distinction, to date. This might require downstream reconfiguration, but it's simply easier to sub-select tests this way, and it's the conceptually better classification for our multi-accelerator tests.

Multi-processor as test/benchmark "layer"

---

include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
src/qstabilizer.cpp
src/qunit.cpp

I still haven't figured out a way to use QStabilizerHybrid under QUnit without converting to ket notation upon measurement, but I have found out that, once measurement of an entangled qubit happens this way, `IsSeparableZ()` no longer works correctly for collapsed qubits. The bug seems to involve an inability to distinguish Z basis eigenstates after "wave function collapse," and this might be a deeper limitation of my attempted use of the stabilizer formalism, rather than a simple bug. However, as we have used QStabilizerHybrid previously and here in this PR, the overall stack works, if not perfectly optimally.

"Tweaking" stabilizer measurement

---

include/qstabilizerhybrid.hpp

As like the earlier PR from today, we're continuing to chip away at easy "land-grabs," to avoid the conversion from stabilizer to ket wherever we can under QUnit.

Do not convert to ket on ForceM() if Z eigenstate

---

src/qunit.cpp

This optimization was intended for just the stabilizer shard case, hence we condition it upon that.

Optimize MAll() for stabilizer shards

---

include/qunit.hpp

Per the "Theory of Qrack Optimization" PDF that I've circulated, buffered phase gates can be dropped when measuring across a full QUnit qubit width. Since CNOT has many optimized conditional branches, compared to a generally phased "inversion" gate, we might as well apply the same principle to inversion gates, by dropping their phase factors.

If measuring, drop inconsequential inversion buffer phase factors

---

src/qunit.cpp

This is just a tiny "tweak" on the last PR, to move a basis reversion into a more opportune place, for optimization.

Move CNOT RevertBasisY() to more opportune place

---

src/qengine/state.cpp

I was taking stock of anything that could be improved in `QEngineCPU`, (particularly now that it's generally "hybridized" with `QEngineOCL`, serving the low qubit width end,) and I noticed a couple of floating point references that were not up to standard.

Removing default and ambiguous floating point references

---

include/common/qrack_types.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
include/qinterface.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qunit.cpp

Per "What Limits the Simulation of Quantum Computers?", (https://journals.aps.org/prx/abstract/10.1103/PhysRevX.10.041038), we were also asked a question during our Unitary Fund talk, about whether we had a quantifiable notion of a "approximate entanglement," with regard to QUnit's Schmidt decomposition. This paper somewhat answers that question, by proposing a simulation technique that treats entanglement as the principle components of SVD in order to throw away small principle components, introducing a proportional error in fidelity, but greatly reducing the computational complexity of calculation the circuit.
The simulation method that the paper develops is similar in principle to using our `Decompose()` method, which is basically parallelized Schmidt decomposition, but for cases of …

SVD improvements

---

include/qstabilizerhybrid.hpp
src/qengine/opencl.cpp
src/qunit.cpp

In converting `ApproxCompare()` to `SumSqrDiff()`, I forgot to handle the case where qubit lengths of the QInterface instances being compared don't match. 4.0 is the theoretical maximum error, so we return this as the result.

Return max square difference from SumSqrDiff() if qubit lengths don't match

---

src/qengine/state.cpp
src/qunit.cpp

I missed one of the length mismatch cases for SumSqrDiff(), in QEngineCPU. Also, QUnit::SumSqrDiff() has been optimized.

SumSqrDiff() QEngineCPU bug and QUnit optimization

---

include/qhybrid.hpp
include/qinterface.hpp
include/qstabilizerhybrid.hpp
src/qengine/state.cpp
src/qinterface/qinterface.cpp
test/tests.cpp

We used to have a "TryDecompose()" method, which we stopped supporting. Per #551, we could use it, again, for new development. The approach used here is not particularly efficient, but the QInterface definition is at least immediately supported for all sub-classes.

TryDecompose(), and SumSqrDiff() debugging

---

include/qinterface.hpp
include/qunit.hpp
src/qunit.cpp
test/tests.cpp

Per #551, this PR optimizes `QUnit::Detach()` so as not to `Compose()` across the target range before "detaching." This should benefit specific use of both `Decompose()` and `Dispose()` for QUnit.

Optimized QUnit Decompose() and Dispose()

---

src/qunit.cpp
test/tests.cpp

Single qubit sub-units are a special case, for QUnit. This PR optimizes to maintain those cases. I need to figure out additional tests, before merging this.

Optimizing single bit Detach() cases

---

src/qunit.cpp

The two edge cases handled as one branch in the last `QUnit::Detach` update can actually happen independently and at the same time.

Break QUnit::Detach two-case conditional into two separate conditionals

---

src/qinterface/qinterface.cpp
src/qunit.cpp

Debugging #553, if the raw QInterface is used rather than a clone, because it is already fully entangled, then all qubits should be ensured to be in top-level mapping order before checking for approximate equality.

Use OrderContiguous() in ApproxCompare() if already fully entangled

---

src/qengine/state.cpp
src/qunit.cpp

The running normalization constant is usually applied during single bit gates; this has been fixed.

Restoring CPU normalization on single gates

---

src/qunit.cpp

If the QUnit is already fully entangled, a copy can be avoided by calling `ToPermBasisAll()` followed by `OrderContiguous()`.

ToPermBasisAll() in QUnit::SumSqrDiff()

---

include/qunitmulti.hpp
test/tests.cpp

As the title, TryDecompose() and TrySeparate() are not yet supported for QUnitMulti. This PR fixes resulting unit tests failures.

TryDecompose()/TrySeparate() not yet supported for QUnitMulti

---

include/qhybrid.hpp
include/qstabilizerhybrid.hpp

In trying to build for Android, I ran into some warnings about unintentional TrySeparate() overloading.

Debug TrySeparate() overloads

---

include/pinvoke_api.hpp
src/pinvoke_api.cpp

For my exploratory work in the Unity3D video game engine, it is useful to have the ability to clone simulators. I have added a corresponding method to the PInvoke API.

Add cloning method to PInvoke API

---

include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
src/qengine/opencl.cpp
src/qengine/utility.cpp

This build option was broken, due to a protected method that was accidentally removed.

Fix -DENABLE_VM6502Q_DEBUG=ON

---

include/qunit.hpp
include/qunitmulti.hpp

This fixes general Mac builds, due to a slight difference between gcc and clang.

Fixing Mac build

---

test/tests.cpp

A signed/unsigned comparison prevents total RP4 compilation. Everything necessary to compile the library for RP4 will be debugged in this PR.

Raspberry Pi 4 debugging: signed/unsigned comparison

---

include/qinterface.hpp
include/statevector.hpp
src/qstabilizer.cpp

Several explicit casts are necessary, for XCode to accept the Qrack library for compilation for iOS.

Debugging iOS build

---

src/qengine/state.cpp

For `SumSqrDiff()`, we can leverage an optimization I wrote a while ago, which lets `QEngineCPU` read faster from state vector objects with certain options turned on, by indicating that parallel read will not involve parallel write.

QEngineCPU::SumSqrDiff need not write to state vectors

---

include/qunit.hpp
src/qunit.cpp

If a Clifford sub-unit qubit is detected to be separable in X, Y, or Z basis, permute through all 3 to find which basis it is in, when attempting to completely separate Clifford sub-units.

Check full X/Y/Z basis for Clifford separability

---

include/qunit.hpp
src/qunit.cpp

`CheckCliffordSeparable()` was intended as a fall-back, if stabilizer sub-units were in a state where immediate representation precluded the applicability of the `Decompose()` method, which is limited to special cases. This standard usage has been re-established, and we use better algorithms to recover separability when we have the opportunity.

More Clifford separability optimizations

---

src/pinvoke_api.cpp

PR #571 left behind a few unused functions in the PInvoke DLL, which can be totally removed.

Removing unused functions in PInvoke DLL

---

src/qunit.cpp

`QUnit::GetQuantumState()` can use the same optimization as `QUnit::SumSqrDiff()`. These and all related usages of this optimization have been debugged.

Debug/optimize GetQuantumState() and related methods

---

src/qunit.cpp

In its final steps, the MAll() method did not allow for skipping non-Clifford sub-units, which are already measured and included in the result.

Fixing segfault in MAll()

---

include/qengine.hpp
include/qinterface.hpp
include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

When the `randGlobalPhase` constructor/factory argument is enabled, Qrack assumes that global (separable subsystem) overall phase factors are physically/computationally arbitrary, since they have no possible effect on Hermitian operator expectation values, and therefore they present a useful symmetry for optimization.
When this same option is turned on, Qrack also, partly as a matter of legacy behavior, randomizes global overall phase factors upon initialization and measurement. This can be totally turned off by `randGlobalPhase = false`, but specific initialization phase, with the optimization option on, can still be passed directly through to another constructor argument, typically. This convention was being missed, in QUnit. Assuming no other great difference, I think this original …

Follow GetNonunitaryPhase() convention with QUnit's QEngineShards

---

include/qengine_cpu.hpp
src/qengine/opencl.cpp

While I do not think this functionality is in use at the moment, edge cases involving `SetAmplitudePage()` can be optimized. As in this PR, `clFinish()`, `clDump()` or equivalent should be called before checking these method's various edge cases, under the design assumption that `QPager` "pages" might need to queue OpenCL events not necessarily from their own methods, as might happen with `Compose()` and related methods.

SetAmplitudePage() edge cases

---

include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
include/qpager.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp
test/benchmarks_main.cpp
test/test_main.cpp

QPager should ultimately fully support all QEngine type constructor options. Now, we support normalization options.

Enable normalization options for QPager

---

src/qpager.cpp

`Compose()` is embarrassingly parallel enough in concept to easily begin to stripe over QPager pages. Much more attention needs to be paid to QPager Schmidt decomposition method optimization, soon.

Optimize QPager::Compose()

---

src/qunit.cpp

The stabilizer sub-unit separability code didn't function properly with normalization on. (That would be the first notable bug I notice in what was tagged as v5.4.) However, this PR fixes that bug, while generalizing the Clifford separability code for use without the normalization option, as well. Performance improvement is possible, for higher width benchmark circuits, but I'm still looking into the upshot of this.

DoNorm stabilizer debug

---

src/qstabilizer.cpp

See #582. This doesn't give immediately obvious benefits in standard benchmark tests, but my guess is that it's the conceptually correct approach,

Use Gaussian elimination to attempt to increase separability opportunities in QStabilizerHybrid

---

src/qunit.cpp

I hadn't looked at this method, recently, at least since `isPauliY` basis was implemented. There still might be gains to be made for commutation across Y basis transformation, but my guess is that flushing X/Y basis in this particular case is probably advantageous, overall. Benchmarks look reasonable, so far.

Relaxing restriction on H commutation with buffer

---

src/qunit.cpp

As this feature was implemented and debugged, over months, many edge cases were excepted from a buffer commutation principle that should work more simply. Most of these cases didn't seem strictly necessary by the intended buffer algebra, (the rules of which can be checked by hand,) but it seemed like other bugs or limitations in the developing implementation needed to "shunted." To vague recollection, I would have still expected one edge cases that needs to be struck, here, but it doesn't seem to cause any problems in random circuit cross entropy tests, to leave that consideration out. I'll check my notes and continue to test, before merging.

Simplify QUnit::CommuteH same/opposite cases

---

src/qpager.cpp
src/qunit.cpp

This improves QPager decomposition. Also, it's become apparent through CI that 8d8ed54 was not actually generally correct, via further cross entropy testing in our suite.

QPager decomposition optimization (and revert bugged 8d8ed54)

---

include/qpager.hpp
src/qpager.cpp

This fixes QPager method overload warnings, on all supported mobile platforms

Fix QPager overload warnings

---

src/qunit.cpp

This condition was already removed from `ApplyControlledSinglePhase` counterpart, and it causes no problem with hybrid stabilizer simulation.

Remove unneeded doSkipBuffer conditional

---

include/qunit.hpp
src/qunit.cpp

Certain "shunts" or "work-arounds" for Clifford "shards" under QUnit can now be removed entirely, due to previous improvements in QUnit with Clifford handling since they were added.

Optimize QUnit Clifford handling

---

.travis.yml
include/qunit.hpp
src/qunit.cpp

I've found a few more cases in which QUnit 2-qubit buffer flushes can be avoided, and another set of cases in which buffers can be combined to result in overall single bit gate application. This might give a little improvement on `test_ccz_ccx_h`, among other benchmarks.

QUnit buffer optimization

---

src/qunit.cpp

Here's more buffer refactoring and optimization.
It stands to reason that surviving inversion buffers, by the point we try to reduce pairs of 2 qubit buffers to single bit gates, could still avoid entanglement if we come across them and combine them. In practice, the `std::find` we do a second time in order to likely still _not_ find an opportunity to combine buffers might hurt our average overall time, though. I'm still running benchmarks, to be sure, but I think skipping the inversions, as this already is, is likely the way to go.

More QUnit Buffer optimization

---

src/qunit.cpp

"AntiCNOT" seems to have unnecessary buffer flushes, based on every comparable method we have at this point. Also, flushes after determining the `except` list could nonetheless still entangle control and target, in which case it is better to skip buffering at the last moment.

Standardize buffer flushes; JIT IS_SAME_UNIT()

---

src/qunit.cpp

AntiCNOT was unnecessarily complicated, before the last PR, but the recent abstraction of buffering in the last couple of days points to AntiCNOT having the same commutivity as CNOT, and this makes theoretical sense. I need to run more rounds of cross entropy tests, at least, but this PR is a conservative change that stands to reason against CNOT, before v5.5 tagging is considered.

AntiCNOT buffering should match CNOT

---

src/qunit.cpp

I was thinking about what makes the buffering and buffer flush conditionals work, with and without reaching the buffering logical branch, and I realized that the exception list doesn't need to be conditioned on whether control and target are not in the same unit, to work generally.

Refactor exception lists for buffer flushes

---

src/qunit.cpp

This has worked in theory for a long time, but there are no longer any impediments in QUnit preventing a purely label-based swap gate.

Purely label-based swap

---

src/qunit.cpp

By inspection of the other singly-controlled gates, this optimization check was missing from AntiCNOT.

AntiCNOT OptimizePairBuffers()

---

src/common/qengine.cl

Working on #611, I came across this bug in IndexedLDA/ADC/SBC/HASH variants of the OpenCL kernels.

Fix OCL 'Indexed' operation type bug

---

include/qengineshard.hpp
src/qunit.cpp

`test_stabilizer` should be clearly classically efficient, with `QUnit` over shards of `QStabilizerHybrid`. It is, if combining stabilizer shards is preferred over buffering Clifford operations, (but less preferential than combining with ket-based "shards").

Suppress singly-controlled buffers in place of Clifford efficiency

---

src/common/qengine.cl
src/qengine/opencl.cpp

This is a better solution to the bug in `Decompose()` that becomes manifest on an Intel HD. The buffers should be initially cleared, before use.

Clear Decompose() buffers on init

---

src/common/qengine.cl
src/common/qheader32.cl
src/common/qheader_double.cl
src/common/qheader_float.cl

The OpenCL kernels were using an outdated concept of REAL1_EPSILON ("min_norm"). Amplitude flooring thresholds are specified in kernel arguments; the epsilon of equality with 0 checks should be the native system epsilon value.

Fix OpenCL REAL1_EPSILON

---

include/common/oclengine.hpp
src/qpager.cpp

I'm experimenting with QPager on multi-accelerator cloud instances, and it seems that, with arbitrary numbers of processing elements, QPager might set a paging threshold above its device size. There's never a reason to set qubits-per-page higher than maximum device allocation, but its easy to restrict page sizes to less-than-or-equal-to the max allocation.

Better smart QPager sizing

---

src/qengine/qengine.cpp

`QEngine` based measurement checks probability, non-deterministically decides its measurement result, then "collapses" the state vector to agree. If the state vector is in a deterministic eigenstate for measurement, then the overhead associated with "collapsing" the state vector can be avoided.

QEngine: don't ApplyM() if no effect

---

src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp

I've just realized that `QPager` is failing several unit tests. It needs to be debugged, ASAP, but I'm also experimenting with optimizing the measurement gate, so that `QPager` is actually at least viable for conventional paged quantum computer simulations, with or without `QUnit` optimizations on top. This implementation should hopefully eliminate some needless multi-accelerator limitations, and I will generally debug `QPager` from the top down, after this, while I experiment with the measurement method.

QPager measure

---

src/qengine/opencl.cpp
src/qengine/utility.cpp
src/qpager.cpp

This seems to fix all remaining unit test failures, for `QPager` (over `QEngineOCL`). There was a problem in the `Clone()` method.

Fix QPager w/ QEngineOCL Clone()

---

include/common/parallel_for.hpp
include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
src/common/parallel_for.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp

Ultimately, `QPager` should readily serve as a stand-in for "Schrödinger method" "canonical" distributed simulation runtimes, if only basic gate functionality is used, including measurement. This PR is already more optimal, and it works, but I'm trying to get a benchmark like `test_ccz_ccx_h` to run on two OpenCL accelerators without needing to move any data between them by bus.

QPager optimization

---

src/qpager.cpp

This sets a better default paging threshold, in `QPager`, (at least when tested on an RTX 2070 Ubuntu system).
It's possible to page single accelerators for higher maximum qubit counts, on simple enough circuits. Try `test_ccz_ccx_h` with raw `QPager`->`QEngineOCL` at higher than maximum single `QEngineOCL` allocation.

Better QPager threshold

---

include/qpager.hpp
src/qpager.cpp

If a control bit is dropped for applications as `QPager::SingleBitGate()`, then the `QEngine` pairs acted on by the method are effectively "meta-controlled."

QPager edge case debugging

---

src/qpager.cpp
src/qunit.cpp

So far, this PR attempts to restore optimized QPager Decompose()/Dispose() variants, by ensuring that page segments are not of identical length to the segment requested to be decomposed. Ultimately, I will address QUnit->QPager unit test failures before merging.

Restore QPager optimized Decompose()/Dispose() variants

---

include/qpager.hpp
src/qpager.cpp
test/tests.cpp

The unit tests sometimes use `SetPermutation()` with values that are higher than the maximum permutation of qubits, apparently. This is usually a nonissue, because all other QInterface instances effectively mask for only the valid part of the permutation, but not QPager. It's simple to make QPager respect this use case, though.

QPager::SetPermutation() was not safe for unit tests

---

test/benchmarks.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.cpp
test/tests.hpp

With this PR, device IDs can be selected for QPager and QUnitMulti with a comma-separated list of integers.
You may use the device ID printed in the header, or `-1` aliases the default device, (in addition to its non-negative device ID). Device indices can be specified more than once, and often should be. For example, to run 2 pages on one device before using a second device, the argument could be `--devices=0,0,1,1`.

Add device list option to tests/benchmarks, for QPager and QUnitMulti

---

include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp

This fixes some bugs in the overall combined QUnit->QStabilizerHybrid->QPager->QHybrid stack. Indexed LDA/ADC/SBC operations might still be bugged, or something related in Grover's search of a lookup table, but this should be significantly more stable, overall.

Debugging QUnit with QPager

---

include/qinterface.hpp
include/qpager.hpp
include/qunit.hpp
src/qengine/qengine.cpp
src/qinterface/gates.cpp
src/qinterface/protected.cpp
src/qpager.cpp
src/qunit.cpp

I found the problem with `QPager::ApplySingleEither()`: `QEngine` was not considering `randGlobalPhase` before making global phase shift optimizations.

Restore optimized ApplySingleEither()

---

src/qpager.cpp

This increases the OpenCL maximum "local" qubits to the maximum for single segment RAM allocation on GPUs. This performs slightly better than 1 qubit fewer than maximum allocation, (a factor of 2 less).

Maximum allocation per segment is best for QPager on RTX 2070

---

README.md
src/qpager.cpp

To choose the number of global qubits contained under a maximum single allocation segment of GPU RAM, as detected, use the environment variable `QRACK_SEGMENT_GLOBAL_QB=n`, where "n" is an integer >=0. The default is 0, meaning single page max allocation is a full GPU RAM segment. A value of 1 would mean 1 "global qubit" per segment, 2^1=2 pages, as opposed to 2^2=4 pages for 2 global qubits, etc..

Add environment variable for choosing QPager segmentation

---

README.md
src/qhybrid.cpp

When `QHybrid` switch-off threshold from `QEngineCPU` is overlapped with paging threshold from `QPager`, favor the threshold of `QPager`.

Smarter QHybrid threshold

---

CMakeLists.txt
cmake/OpenCL.cmake
include/qhybrid.hpp
src/qhybrid.cpp

There is no point in compiling `QHybrid` for use if OpenCL is not enabled. (This also reduces the size of the compiled binary.)

Only include QHybrid if OpenCL enabled

---

cmake/OpenCL.cmake
include/common/config.h.in

I'm debugging SnuCL and VirtualCL clustering. `QUnitMulti` might work, but `QPager` seems to run into issues with cross-node OpenCL buffer shuffling. For now, I notice that the `ENABLE_SNUCL` definition should be permanently fixed in the common configuration header.

Fix ENABLE_SNUCL definition

---

.travis.yml
README.md
include/qpager.hpp
src/qpager.cpp

As stated in the README update, the `QRACK_DEVICE_GLOBAL_QB=n` environment variable lets the user specify a `QPager` performance hint, where n=2 by default.

QRACK_DEVICE_GLOBAL_QB environment variable performance hint

---

include/qengine_opencl.hpp
src/qengine/opencl.cpp

The header inclusions for `QEngineOCL` have been simplified/corrected.

Fix QEngineOCL headers

---

CMakeLists.txt
examples/qneuron_classification.cpp
examples/quantum_associative_memory.cpp
examples/quantum_perceptron.cpp
examples/teleport.cpp
include/common/half.hpp
include/common/qrack_types.hpp
include/qinterface.hpp
include/qneuron.hpp
src/common/rdrandwrapper.cpp
src/pinvoke_api.cpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qengine/state.cpp
src/qinterface/gates.cpp
src/qinterface/protected.cpp
src/qinterface/qinterface.cpp
src/qinterface/rotational.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.cpp

This enables FP16 on x86_64 with the http://half.sourceforge.net/ header, under MIT License. I'm going to test `half` CPU/GPU interoperable `QEngine` types on cloud infrastructure, before merging.

Add http://half.sourceforge.net/ header support

---

README.md
include/common/parallel_for.hpp
src/common/parallel_for.cpp

In addition to specifying the default `PSTRIDEPOW` value at build time, it is now possible to override it with an environment variable at run time.

Add QRACK_PSTRIDEPOW env var

---

include/qpager.hpp
src/qhybrid.cpp
src/qpager.cpp

I missed a couple of occurrences of `PSTRIDEPOW` that needed to be handled as an environment variable.

Handling all occurrences of PSTRIDEPOW as env var

---

src/common/oclengine.cpp
src/qengine/opencl.cpp
src/qpager.cpp
src/qstabilizerhybrid.cpp

(Cherry-picked from #672.)
It's not a case that I've frequently encountered, but it's possible that Qrack is built on a system with the OpenCL library, but no available devices at the time. Actually, it's probably a relatively common scenario, particularly for pre-compiled binaries as in my experiments with packaging the compiled library for Unity, or similarly with our Q# support. We already had an API method to count the available devices, so QHybrid and QEngineOCL sub-layers should always be replaced with QEngineCPU, in this case, at least for defaults.

Check if 0 devices before defaulting to OpenCL

---

.travis.yml

The bug causing segmentation faults was assigning to a child scope set of variables for `QInterface` types rather than the global scope, in the plugin.

Re-enable Qiskit/PennyLane tests

---

CODE_OF_CONDUCT.md

"Qrack has adopted the Unitary Fund Contributor Covenant Code of Conduct. **We love our community, and planet Earth is our community, indiscriminately. You rock!**"

Add Unitary Fund Code of Conduct

---

CODE_OF_CONDUCT.md

I hadn't noticed the other night that I added the Code of Conduct with only the Unitary Fund contact email. I want my personal email address available, here, so you have the option of contacting me personally.
I, Daniel Strano, am basically sole developer of Qrack. The Unitary Fund has generously provided us with a grant. Should you feel uncomfortable contacting me for any reason, about a Code of Conduct violation, I am accountable to the Unitary Fund for this grant. (I hope this is unthinkable, but, in abstract, it isn't.)

Add project lead email to Code of Conduct

---

examples/ordered_list_search.cpp
src/qunit.cpp
test/accuracy_main.cpp
test/benchmarks_main.cpp
test/test_main.cpp

With an OpenCL build, I didn't handle default switching under QStabilizerHybrid when 0 OpenCL devices are available.

Handle switching with 0 OpenCL devices available w/ OpenCL build

---

src/qunit.cpp

This addresses #681, and fixes the relevant Q# unit test.

Debug ProbParity/ForceMParity 1 bit edge case

---

include/qstabilizerhybrid.hpp
src/qstabilizerhybrid.cpp
src/qunit.cpp

Per #683, the domain of `QStabilizerHybrid` shards under `QUnit` has been expanded. If a shard-level single bit gate is not Clifford, gate fusion is attempted on the chance of producing a fused Clifford gate at a later point. For controlled gates, `QUnit` buffering has been conditioned to proactively preserve underlying stabilizer representation in shards. (QFT might be a tiny amount faster, but I don't have a perfect baseline reading on my new development environment.)

Extended stabilizer under QUnit

---

include/qstabilizerhybrid.hpp
src/qstabilizerhybrid.cpp

Similar to the most elementary motivations for `QUnit`, this PR makes `QStabilizerHybrid` check its control qubit states for separable controls that can be removed before applying, so as to convert more gates to Clifford set.

Trim QStabilizerHybrid controls

---

include/qstabilizerhybrid.hpp

We can avoid flushing buffers, in many cases of `QStabilizerHybrid::Prob()`.

Optimize QStabilizerHybrid::Prob()

---

include/qstabilizerhybrid.hpp
src/qstabilizerhybrid.cpp

For extending stabilizer simulation, phase can be ignored, if non-Clifford phase or "inversion" gates act on a Z basis eigenstate.

Extended stabilizer: phase doesn't matter if Z eigenstate

---

include/qstabilizerhybrid.hpp
src/qstabilizerhybrid.cpp

Continuing with the QStabilizerHybrid optimization work of the last few days, we can avoid many unnecessary cases of non-Clifford single bit gate fusion buffer flushing, by only flushing buffers for multi-qubit gates when a target or control bit is blocked by a non-Clifford buffer.

Only flush QStabilizerHybrid on blocked bits

---

include/qengine_cpu.hpp
src/qengine/state.cpp
src/qpager.cpp

I noticed that edge cases were missed, between asynchronous and parallel `QEngineCPU` operation.

Fix async QEngineCPU

---

README.md
include/qpager.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
src/qunit.cpp
test/tests.cpp

Middle qubit ranges have suffered with an optimal stack including `QPager`, compared to `QUnit` without paging. I tried to implement a performance fix for this 2 or 3 other different ways, with hypothetically better separation of concerns, but none of those approaches actually met the requirement of _fixing_ _the_ _performance_. As a result, we're temporarily stuck with this, which shoves a threshold-crossing cost under the rug, in a situation where it's not currently likely to come up.
At 21 qubits overall width, or as specified by the `QRACK_QUNIT_PAGING_THRESHOLD` environment variable, there is a transition under `QUnit` from no paging at lower qubits, to paging at higher qubits. This generally will not be used in flight, with plugins for third party frameworks.

Mid-range performance, with paging

---

include/qengineshard.hpp
src/qunit.cpp

For `ProbParity()` and `ForceMParity()`, if a bit is not cached in Pauli X or Y basis, then a cached phase gate can have no effect on the outcome of these methods. Hence, cached phase gates do not need to be flushed, if a bit is in Pauli Z basis. (Further, these methods do not _collapse_ any observable associated with these cached phase gates, so these cached gates are retained.)
For ProbParity(), if a separable bit is cached in Pauli X or Y basis, we can calculate its effect on parity probability without converting to Z basis.

Optimize prob/measure parity

---

include/qengineshard.hpp
include/qunit.hpp
src/qunit.cpp

As the title and commit message say, "Cached phase gates don't affect `Prob()`." For that matter, neither do cached "inversion" gates where the `Prob()` bit target is a _control_ bit, rather than a target bit. (Amazing that I missed this opportunity for so long, in such a core part of the API).

Cached phase gates don't affect Prob()

---

README.md

I have tested Q# runtime unit tests, at this stage of development, and 64-bit complex amplitudes are not necessary to pass. 64-bit complex amplitudes are always an option, but there's no need to recommend them  in the README for Windows.

Windows doesn't need 64-bit complex, standard

---

src/qstabilizerhybrid.cpp

Using `SetQuantumState()`, `QStabilizerHybrid` attempts to recover a stabilizer state if possible from introspection of a single qubit pair of amplitudes. Now that we have a single qubit fusion buffer system in `QStabilizerHybrid`, it is _always_ possible to cache a single bit as a stabilizer state with or without a single bit fusion buffer. This is mostly important for cases where `QUnit` creates hybrid stabilizer "shards," potentially.

QStabilizerHybrid::SetQuantumState(): Always cache single qubit

---

include/qstabilizerhybrid.hpp
include/qunit.hpp
src/qunit.cpp

This generalizes the potentially successful cases of `QUnit::TrySeparate()` for a single bit. If the bit _can_ be put into a separated representation, under the currently active 2-qubit gate buffers, then this improvement should _always_ do so, within floating point rounding error.
(I also noticed that `QStabilizerHybrid::Prob()` doesn't need to flush single bit buffers if the active buffer is a phase gate, and `QUnit::ApplyEitherControlled()` should first consider whether a single bit buffer is cached, before trying to separate Clifford sub-units.)

More general QUnit::TrySeparate()

---

src/qpager.cpp

There's no point to dispatching a `std::future` for a loop body that only makes async calls to page engines, by design.

Remove QPager std::futures for async page gate calls

---

test/benchmarks.cpp
test/benchmarks_main.cpp
test/tests.hpp

This lets the user select benchmark depth for randomly constructed circuit benchmarks from the command line. (1 unit of depth is 1 round of single bit gates with 1 round of multi-qubit gates, as indicated with the `-?` option text.)

#705: Variable benchmark depth

---

include/qunit.hpp
src/qunit.cpp

I've identified a few additional cases where probability caching for single bits in `QUnit` can be preserved.
For controlled gates, we filter the caching by whether the public method call is a phase gate and whether the target bit is in Pauli Z basis. We miss cases in Pauli X and Y bases, this way, but the comparative complication of implementing those cases might be sufficient reason to leave them out, at least for now.

Improved QUnit caching

---

src/qunit.cpp

This slightly simplifies `QUnit::ApplyEitherControlled()`.

Refactor ApplyEitherControlled()

---

README.md
include/qunit.hpp
src/qhybrid.cpp
src/qpager.cpp
src/qunit.cpp

As a further experiment in "approximate separability," this PR defines an environment variable to directly override `QUnit` floating point threshold for considering a qubit to be in a Z basis eigenstate. It would probably make sense to also have a constructor argument for this, and to only override the constructor variable if the environment variable is defined, but the environment variable alone is more immediately useful for experimentation. The threshold variable takes a floating point value between 0 and 1.
Also, the `direct.h` header on Windows is for directory manipulation; it was erroneously included in several places that didn't use it. It has been removed, there.

QUnit approximate Z basis separability

---

src/qunit.cpp

`QUnit::TrySeparate()` had a problem converting shard types. However, by basically reverting #703, we fix this problem and typically get better performance, even if generality is lost.

Debug QUnit::TrySeparate()

---

include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
include/qpager.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qhybrid.cpp
src/qpager.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp
src/qunitmulti.cpp

As mentioned in #710, we should have both a constructor argument and an environment variable override, for `QUnit` separation threshold.

Add separability threshold constructor argument

---

src/qengine/opencl.cpp
src/qengine/state.cpp
src/qunit.cpp

It is possible for `QEngine` pages under `QPager` to have no allocated state vector RAM, if the total probability in that page is 0. This edge case needs to be anticipated in `QEngineCPU` and `QEngineOCL`, when composing and decomposing.

QPager Compose()/Decompose() debug

---

src/qunit.cpp

When `QUnit` Schmidt decomposes approximately, it "leaks" probability. `UpdateRunningNorm()` and `NormalizeState()` should be called, to compensate.

Normalize if QUnit approximately separates

---

src/qengine/opencl.cpp
src/qengine/state.cpp

For approximate separability tests, these `ZeroAmplitude()` calls in `UpdateRunningNorm()` seem to have been causing crashes.

Don't zero ZeroAmplitudes() from UpdateRunningNorm()

---

include/qinterface.hpp
include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.cpp

I'm still considering coverage for this, and larger numbers of qubits, but the work here should decompose all approximate 1 and 2 qubit stabilizer states upon `TrySeparate()`.

#716: 2-qubit TrySeparate()

---

include/qhybrid.hpp
include/qinterface.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp
test/tests.cpp

I wasn't happy with the coverage or signatures for `TrySeparate()`, from #719.
Since stabilizer states and `QUnit` buffers only extend to 2-qubit gates, at most, it makes sense to have single-qubit and double-qubit signatures for `TrySeparate()`. If the `TryDecompose()` variant is desired for any number of qubits, then specify an explicit error tolerance.
Coverage has been also been improved.

#716: Refactor TrySeparate()

---

include/pinvoke_api.hpp
src/pinvoke_api.cpp

Since `TrySeparate()` variants are now achieving practical returns, it makes sense to expose them to Windows operating system environments in our DLL, as for Unity3D development.

Add TrySeparate() to DLL

---

include/qinterface.hpp
include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

`QUnit` has a better window than user code should on situations in which one might call `TrySeparate()`. Following the general considerations I've thought to try in benchmarks, `QUnit` can aggressively try to separate bits in flight, (i.e. after-the-fact separation, in addition to proactive).
There's no point in making this a constructor argument, because depths of applicability for advantage are on order of 5x 1qb+2qb full layers, which cannot be readily tracked locally in `QUnit` internals. Off by default, `SetAggressiveSeparate(bool)` can be used in user programs to set a range a usefulness for reactive `TrySeparate()` attempts.

QUnit::isAggressiveSeparate

---

include/qstabilizerhybrid.hpp
src/qinterface/gates.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp

`qrack_types.hpp` defines `real1` compatible `sqrt(2)` and `1/sqrt(2)` macros. Now, we use these throughout.

Replace M_SQRT2 and M_SQRT1_2 constants

---

src/qunit.cpp

This adds a `BLOCKED_SEPARATE()` macro in `QUnit` to check whether stabilizer representation is ready for decomposition. Replacing instances of the macro lead me to fix a bug in `ForceM`.

Add BLOCKED_SEPARATE() macro (and fix ForceM bug)

---

src/qunit.cpp

The use of `IS_NORM_0()` in `QUnit` was confused between amplitude and gate clamping. We turn these two cases into distinct macros, in this PR.

Differentiate IS_AMP_0() macro

---

src/qunit.cpp

When the rounding threshold parameter is turned up higher than (1 - 1/Sqrt(2)) / 2, secant volumes of the single-qubit Bloch sphere can overlap. In this case, a state might qualify to round to one Pauli axis pole while having a larger projection on another single qubit basis, but there's no way to know without trying all 3 Pauli bases.

Fix secant overlap between mixed Pauli states

---

include/qunit.hpp
src/qstabilizerhybrid.cpp

When switching to and from Pauli Y basis, do it as a single gate, depending on stabilizer vs. Schrödinger method.

Perform Pauli basis transformations as single gate

---

include/qstabilizer.hpp
src/qinterface/gates.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp

When parity methods are called with masks with a single bit set, they become single bit non-parity method cases.

Parity method optimization

---

include/qunit.hpp
src/qunit.cpp
test/benchmarks.cpp

Thinking about `TrySeparate()` to 2 qubits at once, we want decompose a potential Bell pair that has been transformed into any local qubit X/Y/Z basis. If we assume we are given a Bell pair, we probably want to try all of CZ/CX/CY to decompose it, progressively as any previous attempts fail.
With `QUnit`->`QPager`->`QHybrid`, on a machine capable of doing 30 fully entangled qubits, this seems capable as taking depth=4 circuits of `test_ccz_ccx_h` to a very rough neighborhood of 50 qubits or higher. Single basis decomposition attempts did not seem nearly as likely to accommodate this width.

3-basis 2 qubit TrySeparate

---

src/qunit.cpp

If we're reactively separating in `QUnit`, we prefer maximum explicit separability of representation over a small multiplier on stabilizer execution cost, while the reactive separation mode is set.

Proactively maintain stabilizer separation when reactively separating

---

test/benchmarks.cpp

With the new "reactive" (and optionally approximate) separability improvements, I'm looking for candidate gate sets to benefit. This adds a benchmark for stabilizer gates plus `T` gate. (I think I can safely say,) this is a universal gate set.
Assuming we want the fastest route to arbitrary linear discrete phase factor gates, equal weight on `Z`, `S`, and `T` makes sense. `Swap` gate, as a fraction of switch-off from `CNOT`, is estimated by 3 bits of uniformly random `CNOT` permutation outcomes with a degeneracy of 1 bit, hence (2^-3)/2^-1=1/4 likelihood of occurring via a series of uniformly random `CNOT` gates over 2 bits, (only swapping control/target).

"Stabilizer+T" benchmark

---

include/qstabilizer.hpp
src/qstabilizerhybrid.cpp
test/benchmarks.cpp

This adds the `CY` gate to hybrid stabilizer simulation, for inclusion in the `test_stabilizer_t` benchmark, and generally.

Stabilizer CY gate

---

include/qinterface.hpp
include/qstabilizerhybrid.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
src/qstabilizerhybrid.cpp
test/benchmarks.cpp
test/tests.cpp

In the search for a more representatively general benchmark, I'd like to have `test_stabilizer_t` variants with and without doubly-controlled gates. (This still works above Schrödinger' method limits.)

Add test_stabilizer_t_cc

---

include/pinvoke_api.hpp
src/pinvoke_api.cpp

This is HPC territory, but I'd like to experiment with exposing `SetReactiveSeparate()` through our DLL, as for Unity3D integration. (Even at less than HPC scales, it could prove to be a useful optimization, both in "game world space-time" and as a back end plugin.)

Expose SetReactiveSeparate() through DLL

---

include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
src/qstabilizerhybrid.cpp
test/benchmarks.cpp

The `SqrtX` gate, and its adjoint, can be handled as stabilizer.

Stabilizer SqrtX/SqrtY

---

src/qstabilizerhybrid.cpp

`!wasCached` was used for `ApplySinglePhase()` and `ApplySingleInvert()` since they divert to `QEngine` optimized cases. All other diversion cases should be directly to stabilizer, of which only `H()` was left.

Stabilizer phase/invert optimization and debug

---

test/benchmarks.cpp

In addition to `T` as a subdivision of `Z`, I have added the equivalent of `T` as subdivision of `X` and `Y`.

Add X^(1/4) and Y^(1/4) to benchmarks

---

test/benchmarks.cpp

Rather than self-penalize for ease of expression, we can compose `X`/`Y`/`Z` root gates in a minimum of depth, in benchmarks.

Refactor single bit decompositions for minimum depth

---

src/qstabilizerhybrid.cpp

Calling directly into `stabilizer` in these cases misses flushing single bit fusion buffers.

Flush single bit fusion stabilizer buffers on control bit elimination

---

src/qstabilizer.cpp
src/qunit.cpp

It shouldn't be necessary to entirely avoid "shard" separation for Clifford sub-units, but this shunts a bug came across in Q# unit tests with QUnit.

Fix Q# SWAP 2 qubit test

---

test/benchmarks.cpp

`test_stabilizer_t_nn` (universal nearest-neighbor) is a good test, but `QUnit` might perform even better with the option of 3 qubit gates. This benchmark tries to pack random selections between 2 and 3 qubit gates as tightly as possible. For simplicity, all three qubit gates are "straight lines" on the virtual chip, as opposed to potentially at right angles from the center bit.

Nearest-neighbor benchmark with random 2/3 qubit gate selection

---

.travis.yml
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp

A bug in `CanDecomposeDispose()` was the reason Clifford separability wasn't working correctly.

Debug stabilizer CanDecomposeDispose()

---

src/qunit.cpp

In 2 qubit `TrySeparate()`, successively try and revert `CNOT, CY, CZ` on a fixed single qubit basis for control and target, while iterating through single bit bases for each controlled gate option to check for separability. If `a` and `b` of `TrySeparate(a, b)` are the only 2 qubits represented in their sub-unit, only iterate through one bit's Pauli bases to check for separability.
I can't tell whether this an ideal `TrySeparate()` implementation for decomposing Clifford states, yet. I expect to amend around `TrySeparate()` more in the next few days, but this seems to be an improvement for now.

TrySeparate(a, b) refactor

---

include/qunit.hpp
src/qunit.cpp

I'm testing this for performance. It passes Q# unit tests.

Leave TrySeparate() qubits in best projection if isReactiveSeparate

---

src/qunit.cpp

This occasionally separates a single qubit that is not in an X/Y/Z basis eigenstate, to start.

TrySeparate(a) continuous basis change optimization

---

include/qinterface.hpp
include/qunit.hpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
src/qinterface/rotational.cpp
src/qunit.cpp

Single separable bits do tend to stay in RX and RY directions, it turns out. To an extent, this is an artifact of benchmark gate sets, but those gate sets should at least have very uniform coverage on the single qubit subspaces within them.

RX and RY test for separability

---

src/qengine/opencl.cpp
src/qengine/state.cpp

I'd really like to be able to deallocate "pages" when a running normalization check finds that the probability-in-page is 0. To do so, it's helpful if _all_ `QEngineCPU` and `QEngineOCL` methods are safe for internal use by `QPager`. We're not 100% there, yet.

Add more CHECK_ZERO_SKIP() handling to QEngine subtypes

---

src/qengine/opencl.cpp
src/qengine/state.cpp

When `QEngine` types are used as `QPager` "pages," they might compose with another page that has 0 overall probability within it. If so, we know the `Compose()` operation will lead to a product state with 0 total internal probability represented, and we can deallocate the RAM for this page.

Call ZeroAmplitudes() as opportune for Compose()

---

src/qunit.cpp

This is an optimized case, for `QUnit::TrySeparate(a)` with error tolerance.

Divert TrySeparate(a) for length==1

---

include/qunit.hpp
src/qinterface/qinterface.cpp
src/qunit.cpp

In `QUnit` internals, `TryDecompose()` should catch all cases of separable single qubits that Clifford basis checks miss. However, this check is extremely expensive, compared to Clifford basis checks only. However, simulated experimental probing suggests that, on the unit circle, under arbitrary rotation of a separable pure state, the root-mean-square of probability vector length along 3 orthogonal axes (as calculated herein) is never less than 1/2.

"Litmus test" for brute force TryDecompose()

---

include/qstabilizerhybrid.hpp
include/qunit.hpp
src/common/qengine.cl
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qinterface/qinterface.cpp
src/qpager.cpp
src/qunit.cpp

Not only will this make `SumSqrDiff()` faster, but it bases the return value upon the square norm of the inner product between compared states, such that _all_ representations that are equivalent in the expectation values of all Hermitian operators will be recognized as the same state, when compared.

Optimize SumSqrDiff()

---

include/qinterface.hpp
src/common/qengine.cl
src/qengine/opencl.cpp
src/qengine/state.cpp

After #801, an arbitrary overall phase factor introduced by `DecomposeDispose()` is no longer of consequence.

Optimize DecomposeDispose()

---

include/qunit.hpp
src/qunit.cpp

With the rapid changes, today, this revert might turn out to be more universal in practicality (but slightly slower) after all. I'm still testing.

'Litmus test' for brute-force TrySeparate(a)

---

src/qunit.cpp

In the early days of `QPager`, the (better) default implementation here didn't work, but this has been corrected, at some point over the course of months of cumulative development.

ZeroPhaseFlip shunt no longer necessary

---

README.md
include/common/oclengine.hpp
include/qengine_opencl.hpp
src/common/oclengine.cpp
src/qengine/opencl.cpp
test/benchmarks.cpp

This adds a global maximum allocation guard to `OCLEngine()`, with the ability to reset it after exceptions.

Global max allocation guard

---

include/common/oclengine.hpp
include/qengine_opencl.hpp
src/qengine/opencl.cpp

The point of this PR is for allocation guards to serve as conservatively and tightly against real active allocation as possible. Total allocation tracker should always be incremented _before_ actual allocation, and the tracker should always be decremented _after_ free.

Improve OpenCL allocation guards

---

include/common/oclengine.hpp
include/qengine_opencl.hpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qinterface/arithmetic.cpp
src/qinterface/gates.cpp
src/qinterface/qinterface.cpp
src/qinterface/rotational.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp

This has been a problem, with the recent work on allocation guards. When exceeding allocation limits, we now throw in `QEngineOCL`, _after_ de-allocating all heap resources.

Fix mem leak on throw std::bad_alloc()

---

include/qunit.hpp
src/qstabilizerhybrid.cpp
src/qunit.cpp
test/tests.cpp

To debug `SetReactiveSeparate(true)` with mirror circuits, I need to unravel the tangle of `QUnit` Pauli basis buffering, which should not rely on state variables such as `freezeBasisH` across `QUnit` to do its job.

QUnit Pauli basis refactor

---

include/qstabilizerhybrid.hpp
src/qstabilizerhybrid.cpp
src/qunit.cpp
test/tests.cpp

Do not attempt to separate stabilizer shards in `ApplyEitherControlled()`.

Fix `test_mirror_circuit_10`

---

include/qstabilizerhybrid.hpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp

All `void` return gate methods in `QStabilizerHybrid` that are not `QInterface` trunk can now be cut without loss of performance, hypothetically.
Since we have "shards" for single qubits already in `QStabilizerHybrid`, rather than store a corresponding `shardsEigenZ` vector alongside to complement, just store this `bool` on the shards themselves. This must always be appropriately set, whenever we call `make_shared<QStabilizerShard>()`.
I am unit testing locally before merging, including with Qiskit. I will deal with "Travis-ocalypse" this weekend.

QStabilizerHybrid refactor - cut redundant code

---

README.md

In the readme, inconsistency in formatting styles for keywords such as QUnit, QEngine, etc. is seen where in some cases, it is enclosed with quotes and in others, it is enclosed as inline code.
This PR fixes this inconsistency and renders all such keywords as markdown formatted inline code.
Also made some minor formatting changes to README.

Added inline code to `README`

---

src/qengine/opencl.cpp
src/qpager.cpp

This is unit test verified intermediate work, in the process of debugging `QPager`->`QEngineOCL`.

wait_refs safety; debug QPager::Compose(toCopy, start)

---

src/qengine/opencl.cpp

For consistency, all internal `QEngineOCL::Finish()` calls can be replaced with (protected) `clFinish()`. (This should make no difference, as the code stands, but it hypothetically allows us to differentiate between asynchronous GPU `clFinish()` and a potential CPU asynchronous dispatch, as in `QEngineCPU` and `QStabilizerHybrid`.)

All internal OCL Finish(), changed to clFinish()

---

src/common/qengine.cl

OCL constant address space might have ~64KB max single allocation.

Don't exceed OpenCL `constant` address space size limits.

---

include/hamiltonian.hpp
src/qunitmulti.cpp

The fact that the last LGTM error wasn't fixed by #854 doesn't make sense, given the suggestion notes from them. I'm testing if LGTM was tripped up on the degenerate syntax, of `const type& x` as opposed to `const type &x`.

LGTM refactor

---

include/pinvoke_api.hpp
include/qinterface.hpp
src/pinvoke_api.cpp
src/qinterface/qinterface.cpp
test/benchmarks.cpp
test/tests.cpp

For stability in the Unity game engine, this removes `SetReactiveSeparate()` thresholds from the PInvoke API, (which brings it into line with recent changes in the general library,) and it adds a simple (but not necessarily performant) method for quickly checking the permutation expectation value of an arbitrary list of bit indices.

Unity debugging/improvement

---

include/common/qrack_types.hpp
include/qpager.hpp
src/common/qheader_bcd.cl
src/qengine/arithmetic.cpp
src/qpager.cpp
src/qunit.cpp

The `QUnit` layer has a qubit count activation threshold, before it will use an intermediate `QPager` layer for its "shards." If `QUnit` qubit width changes, there is a switch-over process, where all shards gain an intermediate `QPager` layer. Previously, this caused redundant allocation in `QPager`, before "locking" the old shard and splitting it into pages.
This PR adds a constructor to `QPager` that lets `QUnit` turn on an interstitial paging layer without generating redundant state vector garbage, by directly locking a `QEngine` as its first "page."

New QEngine-locking QPager constructor

---

src/qengine/opencl.cpp

Nearly all `QEngineOCL` method calls themselves internally call `QueueCall()` or `WaitCall()` to dispatch the payload kernel. It is probably preferable to always allow OpenCL to decide when to flush the command queue, otherwise.
A method like `SetAmplitude()`, for setting single amplitudes of the wave function state vector, does not call `QueueCall()` or `WaitCall()` and therefore does not flush. However, should OpenCL actually defer `SetAmplitude()` command queue dispatch, it might achieve _batching_ on otherwise inefficiently slow single work items, as on a sequential string of amplitude writes.

OpenCL tweak

---

src/common/oclengine.cpp

I have added `-cl-strict-aliasing` to the OpenCL compilation optimization flags. (I think we never alias any pointer range, in kernels.) I considered removing `-cl-denorms-are-zero`, but denorms are smaller absolute value than our suggested minimum single amplitude values per FP type, in `qrack_types.hpp`.

Tweak OpenCL compile options

---

src/common/oclengine.cpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.hpp

(We had this previously, but I didn't see actual use for it, until now:)
We add an option to the benchmark executable to allow users to require that OpenCL state vector buffers are allocated in general heap. I'm not so lucky, with my personal devices, but this could sometimes allow the use of greater general heap capacities than GPU internal VRAM, potentially including swap space, dependent on DMA capabilities of the GPU/system.

OpenCL host pointer option in benchmarks

---

include/qhybrid.hpp
include/qstabilizerhybrid.hpp

Overloads of `ExpectationBitsAll()` in the optimal stack were still being diverted to the default implementation in the public interface. This PR is _much_ faster.

Fixed all overloads for ExpectationBitsAll()

---

include/pinvoke_api.hpp
src/pinvoke_api.cpp

This directly exposes 2x2 complex matrix gate definitions via the PInvoke API. (It is worth noting that Qrack intends, by design, to divert these method calls to "phase," "invert," and even gate-fusion-over-Clifford gates, etc., when it can.)

PInvoke `Mtrx()` methods

---

examples/grovers.cpp
examples/grovers_lookup.cpp
examples/ordered_list_search.cpp
examples/pearson32.cpp
examples/qneuron_classification.cpp
examples/quantum_associative_memory.cpp
examples/quantum_perceptron.cpp
examples/shors_factoring.cpp
examples/teleport.cpp
include/qfactory.hpp
include/qpager.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/pinvoke_api.cpp
src/qengine/utility.cpp
src/qhybrid.cpp
src/qpager.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp
src/qunitmulti.cpp
test/accuracy.cpp
test/accuracy_main.cpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.cpp

This addresses #661. The old factory signatures are still supported, as well, so this should not be a breaking change.

#661: Refactor qfactory.hpp with vector of QInterface types

---

CMakeLists.txt
examples/grovers_lookup.cpp
include/pinvoke_api.hpp
src/pinvoke_api.cpp

This adds all relevant, pre-existing arithmetic methods to the shared library, conforming to the shared libraries' conventions for qubit indexing and function signatures. ("Carry" variants are rendered redundant by arbitrary bit "pile" access, except for `IndexedADC`/`IndexedSBC`.) I'm still debugging this, but I want to start the CI, now.

Add ALU to shared library.

---

README.md
include/common/oclengine.hpp
include/qengine_opencl.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/common/oclengine.cpp
src/qunit.cpp
src/qunitmulti.cpp

The default behavior of `QUnitMulti` has been changed. To turn **on** reactive redistribution of device shard load, (which used to be **on** by default, but is now **off** by default,) set the `QRACK_ENABLE_QUNITMULTI_REDISTRIBUTE` environment variable to any value except the null string.
Also, `QUnitMulti` now **proactively** distributes and balances load, whenever there is a request to create a new shard engine.

`QUnitMulti` environment variable

---

include/pinvoke_api.hpp
src/pinvoke_api.cpp

I love how beautifully succinct the shared library is, while exposing almost _all_ the optimization and universality of Qrack. I noticed a few key API methods might have still been missing. We don't want to add _anything_ redundant in this API, if we can help it, but I think this PR basically exposes the _full extent_ of _optimal_ and _direct_ Qrack, to date, with these particular methods.

Extend shared library API

---

src/pinvoke_api.cpp

I'm in the middle of testing that this is totally stable with threads for PyQrack. Since we already observe lock guards on OpenCL kernel call argument hooks, deep in `QEngineOCL`, we shouldn't need any more mutual exclusion for parallel access to different simulator instances at the C shared library interface level.

PInvoke simulator parallelism

---

src/pinvoke_api.cpp

With a mutex per simulator, and a meta-level mutex for STL containers associated with simulators, it should be possible to use simulator instances concurrently in different threads, above the shared library level, without unnecessary blocking.

Shared library interface mutexes

---

include/qpager.hpp
src/qpager.cpp
test/tests.cpp

I'm still thinking about this fix, but I want to start the CI process. In `QPager::PhaseParity()`, if the page being operated on has odd parity among just the "global qubits" in the mask, then the phase factor is flipped, between the "local qubit" on/off permutations. Otherwise, with even parity of "global qubits," the phase factor is simply directly based upon the "local qubit" on/off permutations.

`QPager::PhaseParity()` debug

---

include/pinvoke_api.hpp
src/pinvoke_api.cpp

This add the option to disable Schmidt decomposition upon simulator initialization, in the shared library interface.

Option to disable shared library Schmidt decomposition

---

include/qinterface.hpp
src/qbinary_decision_tree/tree.cpp

This PR changes `QBinaryDecisionTree` (and adds default virtual `QInterface` decompositions) to handle _all_ starting index cases, for `QBinaryDecisionTree` `Compose()`/`Decompose()`/`Dispose()`.

Generalize `QBinaryDecisionTree` Schmidt decomposition

---

include/common/parallel_for.hpp
include/common/qrack_types.hpp
include/qbinary_decision_tree.hpp
include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
include/qmaskfusion.hpp
include/statevector.hpp
src/common/parallel_for.cpp
src/qbinary_decision_tree/tree.cpp
src/qengine/arithmetic.cpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qengine/state.cpp
src/qinterface/rotational.cpp
test/tests.cpp

In terms of type safety, I've realized that everything descending from `QEngine` or, equivalently, assuming a _state vector_ representation of a quantum computer simulation should strictly use `bitCapIntOcl` as its masking type, except in public method interfaces. (QUnit, for an alternative example, still strictly uses `bitCapInt`, for masking.)
If my original concern was whether `size_t` indexing of arrays would ever exceed 64 bits, the simple and clear answer is "never." The caveat is that we would expect a fully supported set of 128-bit integral types in the compiler first, but 128-bit addressing would have a maximum addressable RAM of something like _2^70 times all the RAM currently in existence on the planet_, so it's moot. (Let's not forget what brings us here, in the first place.)

`size_t` equivalent types should be `bitCapIntOcl`

---

include/qbinary_decision_tree.hpp
src/qbinary_decision_tree/node.cpp
src/qbinary_decision_tree/tree.cpp

I'm still new to the terminology and concepts of quantum binary decision trees, but, based upon https://arxiv.org/abs/1911.12691, I think this PR naturally reaches for an optimization that is what is referred to as a "compute table." As a result, potentially _much_ less "garbage" is generated, in dead `shared_ptr` instances.

Compute tables

---

include/qbinary_decision_tree.hpp
src/qbinary_decision_tree/tree.cpp

`QBinaryDecisionTree` currently relies on fallback to state vector simulation for a very limited set of its API. To avoid (eager) redundant cyclical conversions to and from state vector representation, wait (until just-in-time) to convert state vector simulations back.

(QBDT) Revert from state vector just-in-time

---

include/qbinary_decision_tree.hpp
src/qbinary_decision_tree/tree.cpp

Despite the "compute tables" PR yesterday, `zeroMasks` wasn't actually being reused between inner or outer loop iterations. I will do more research into this method but, for now, we just remove the lines of code that weren't even being engaged.

Remove `zeroMasks`

---

include/qbinary_decision_tree.hpp
src/qbinary_decision_tree/tree.cpp
src/qunit.cpp

For use under `QUnit`, (or in general,) `QBinaryDecisionTree` now has a switch-over threshold from state vector as a more efficient alternative for narrower widths. To recover the original behavior, set the environment variable `QRACK_BDT_THRESHOLD` to `0`. By default, binary decision tree methods will engage in `QBinaryDecisionTree` instances that are 31 qubits or greater in wifth, (equivalent to a `QRACK_BDT_THRESHOLD` of 30).

QBDT vs. state vector threshold

---

include/qengine_opencl.hpp
include/qhybrid.hpp
include/qinterface.hpp
include/qmaskfusion.hpp
include/qpager.hpp
include/qstabilizerhybrid.hpp

This converts the return type of `OCLEngine::GetDeviceID()` from `int` to `int64_t`.

`int64_t` GetDeviceID()

---

include/common/complex16x2simd.hpp
src/qengine/state.cpp

This refactors Apply2x2() CPU "kernels" into macros, shortening the code without sacrificing performance. It also adds a new intrinsic norm calculation for `double` precision, further simplifying and shortening the "kernel" implementations.

Refactor Apply2x2() kernels into macros

---

include/pinvoke_api.hpp
src/pinvoke_api.cpp

In considering how PyQrack should handle C++ exceptions, it occurred to me that a C external interface probably should not raise _C++11 exceptions_ at all, past the top level of the API. For PyQrack, likely, the `QrackSimulator` will poll the error code and re-throw a Python exception.

Shared library exception handling

---

include/qstabilizerhybrid.hpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp

There might be a particularly bad bug in the Windows compiler implementation of `std::swap()` for `std::vector<std::vector<bool>>` elements, which affects our `QStabilizer` implementation. I hesitate to add a partial workaround I have for that, because it seems unlikely that this particular case of `std::swap()` would be bugged, and we might rather have something like a segmentation fault corrupting `std::vector<std::vector<bool>>`. I need to do more research into the issue, before I address the primary  bug. However, this entailed minor style refactoring that can go in immediately.

Windows stabilizer debug

---

include/qengine.hpp
include/qinterface.hpp
include/qpager.hpp
include/qstabilizerhybrid.hpp
src/qengine/qengine.cpp
src/qinterface/arithmetic.cpp
src/qpager.cpp

This add several gate-based default arithmetic logic unit ("ALU") implementations to `QInterface`.

Arithmetic default implementations

---

include/qbdt.hpp
include/qbdt_qinterface_node.hpp
src/qbdt/tree.cpp

Except for `QBdt` methods that revert to a (separate) ket representation, `QPager` at the lowest tree level of a `QBdt` works! (For example, `[mirror]` unit test suite works.)

#944: QBdt QEngine node

---

include/qbdt_node_interface.hpp
src/qbdt/tree.cpp
src/qinterface/qinterface.cpp

Towards #944, this PR totally generalizes `QBdt::Compose()` over insertion indexes and `Attach()` state, with recursion.

#944: Recursive QBdt::Compose()

---

src/pinvoke_api.cpp

pinvoke_api: remove unused variables.

---

include/qbdt.hpp
src/pinvoke_api.cpp
src/qbdt/tree.cpp
test/tests.cpp

Per #954, I notice that `QBdt::Attach()` is _very_ bugged for a ket simulator attachment. In general, we probably need to revert and complete d742e03 for this to work, via `PushStateVector()` and `PopStateVector()`, by multiplying out amplitudes to full tree depth. This is surmountable, but the need to multiply out amplitudes would seem to limit our ability to attach stabilizer representation. However, if we limit our gate set to entirely Clifford/Pauli, `QStabilizer` attachments **already work**, (about 98% of the time on `test_mirror_quantum_volume` if "hacked" for only stabilizer gates, to 100%, indicating that there is only a small bug, at most). There seems to be a symmetry to stabilizer sub-states that precludes the need for `PushStateVector()` and `PopStateVector()`.
Seeing as …

Only allow QStabilizer to QBdt::Attach()

---

src/pinvoke_api.cpp
test/tests.cpp

If we limit to just `QStabilizer` attachments to `QBdt`, as we do not `PushStateVector()` or `PopStateVector()` to multiply-out amplitudes, we also do not normalize stabilizer phase per usual `QBdt` rules. (If we limit `test_mirror_quantum_volume` to just Clifford and Pauli gates, this now seems to have a 100% success rate.)

QBdt stabilizer phase debug

---

include/qbdt_qinterface_node.hpp
include/qstabilizer.hpp
src/pinvoke_api.cpp
src/qbdt/qinterface_node.cpp
src/qbdt/tree.cpp
src/qstabilizer.cpp
test/tests.cpp

It turns out, Aaronson's original implementation of stabilizer tableau seems to freely factor out non-observable global phase offset. (Why wouldn't it?) However, we need to track global phase offset as non-arbitrary for `QBdt` attachment. (This PR makes `test_cfulladd` and tests for related adder circuits pass, for example.)

QBdt Attach() debug

---

CMakeLists.txt
cmake/Qbdt.cmake
include/qbdt.hpp
include/qbdt_node_interface.hpp
include/qbdt_qengine_node.hpp
include/qbdt_qinterface_node.hpp
include/qpager.hpp
include/qstabilizerhybrid.hpp
src/pinvoke_api.cpp
src/qbdt/node.cpp
src/qbdt/node_interface.cpp
src/qbdt/qengine_node.cpp
src/qbdt/qinterface_node.cpp
src/qbdt/tree.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp
test/tests.cpp

`QBdt` can almost correctly `Attach()` to `QEngine` types. In fact, gate primitive unit tests generally pass with "attached" qubits, except for mirror circuit integration tests.
In the meantime, `QBdt` has been significantly improved, by using a `std::set` to skip branching on gate depth node peers. `QPager` and `QStabilizerHybrid` also now provide preliminary for support for the `QEngine` polymorphism.
Finishing `QBdt::Attach()` support might take about a week or so, but everything besides that, herein, is unaffected or improved, including simple `QBdt` simulation.

QBdt improvements (#954)

---

src/qbdt/tree.cpp

One qubit gates do not require branching from above, but controlled gates do. This doesn't completely fix `Attach()`, and, in fact, it makes the `test_mirror_near_clifford` success rate lower, but this likely because we have only first exposed the `QEngine` usage in nodes as surface area for debugging.

QBdt debugging/optimization

---

include/common/dispatchqueue.hpp
include/common/parallel_for.hpp
include/common/rdrandwrapper.hpp
include/qengine.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qinterface.hpp
include/qmaskfusion.hpp
include/qpager.hpp
include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
include/qunitmulti.hpp
src/common/dispatchqueue.cpp
src/common/rdrandwrapper.cpp
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qengine/state.cpp
src/qmaskfusion.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp

This doesn't seem to grossly affect execution speed or binary size, but this is close to a reasonable standard for inline methods. (Per #966.)

#966: Reorganize inline methods

---

include/qbdt.hpp
include/qengine_cpu.hpp
include/qengine_opencl.hpp
include/qhybrid.hpp
include/qinterface.hpp
include/qmaskfusion.hpp
include/qpager.hpp
include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
include/qunitmulti.hpp
src/pinvoke_api.cpp
src/qbdt/tree.cpp
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qhybrid.cpp
src/qmaskfusion.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp
src/qunitmulti.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.hpp

We will likely never need 2^64+ bits of OpenCL device addressing in our lifetimes, or many lifetimes after. However, conceivably, we could at some time exceed 2^32 devices, (or 2^31, with sign degeneracy in Qrack). By finishing the already vestigial shift toward the assumption of 64-bit device indices, we future-proof this, probably forever, even if the OpenCL standard might assume 32 bits of device enumeration, for now.
I need to make sure this works with XACC. If it doesn't, I will hold off on merge, to also update the XACC plugin. However, I'm guessing this probably won't break that build, and then I'll be merging, shortly.

int64_t OpenCL device count

---

include/qbdt.hpp
include/qstabilizerhybrid.hpp
src/qbdt/node_interface.cpp
src/qbdt/qengine_node.cpp
src/qbdt/tree.cpp
src/qstabilizerhybrid.cpp
src/qunit.cpp
test/test_main.cpp
test/tests.cpp

This branch debugs and optimizes `QBdt` layer generally, making it appropriate as an alternative to `QPager` for OpenCL single-device environments. By default, `--optimal` settings will use `QBdt` as an analogue to replace `QPager`. If multiple OpenCL devices are specified for utilization, via environment variables or statically linked constructors, then `QPager` will still be used as the default option instead of `QBdt`.

QBdt in default optimal stack (for single-device environments)

---

src/qbdt/tree.cpp
test/benchmarks.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.hpp

Originally, `QBdt` supported a state vector simulation of a high-index subsystem; this PR debugs and restores that feature.

Hybrid QBdt

---

include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp

This temporarily disables parallel `QStabilizerHybrid::MAll()`, but it largely or fully debugs the new work.

Stabilizer debug

---

CMakeLists.txt
include/qbdt.hpp
include/qbdthybrid.hpp
include/qfactory.hpp
include/qinterface.hpp
include/qstabilizerhybrid.hpp
src/pinvoke_api.cpp
src/qbdt/tree.cpp
src/qbdthybrid.cpp
src/qstabilizerhybrid.cpp
test/benchmarks_main.cpp
test/test_main.cpp
test/tests.cpp

While we've tried various "hybridizations" of quantum binary decision diagrams (QBDD) with state vector simulation and other methods in the past, they as of yet have not given any compelling practical advantages in general use cases, as best the Qrack team can assess.
Trying a slightly different approach with the new `QBdtHybrid`, this might remain the case, like for the quantum Fourier transform or random circuit sampling. However, holistic integration with the overall "layer stack" seems significantly improved, with this approach, and special-case advantages might improved. (We still need to collect additional benchmark data, to test this.)

QBdtHybrid

---

include/qcircuit.hpp
include/qengine_cuda.hpp
include/qengine_opencl.hpp
include/qfactory.hpp
include/qneuron.hpp
include/qstabilizerhybrid.hpp
include/qtensornetwork.hpp
include/qunit.hpp
include/qunitclifford.hpp
include/statevector.hpp
src/common/dispatchqueue.cpp
src/common/functions.cpp
src/common/oclengine.cpp
src/pinvoke_api.cpp
src/qbdt/tree.cpp
src/qcircuit.cpp
src/qengine/arithmetic.cpp
src/qengine/cuda.cu
src/qengine/opencl.cpp
src/qengine/qengine.cpp
src/qengine/state.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qstabilizerhybrid.cpp
src/qtensornetwork.cpp
src/qunit.cpp
src/qunitmulti.cpp
src/wasm_api.cpp

This PR replaces all instances of the `!size()` pattern (for a vector) with `empty()`, commonly used for conditionals all throughout Qrack. Ternary expressions on `size()` have also had their order reversed, to use `empty()`.

Replace !size() pattern with empty()

---

CMakeLists.txt
doxygen.config
include/pinvoke_api.hpp
include/qinterface.hpp
include/wasm_api.hpp
src/pinvoke_api.cpp
src/qinterface/qinterface.cpp
src/wasm_api.cpp

This adds a method for calculating expectation values of tensor products of Pauli operator observables, and it wraps them for the shared library interfaces.

Pauli expectation values method

---

include/pinvoke_api.hpp
include/qbdthybrid.hpp
include/qinterface.hpp
include/qpager.hpp
include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
include/qunit.hpp
include/qunitclifford.hpp
include/wasm_api.hpp
src/pinvoke_api.cpp
src/qinterface/qinterface.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qunitclifford.cpp
src/wasm_api.cpp

This PR rounds out support for completely general single-qubit expectation value and variance queries.

General single-qubit observables

---

CMakeLists.txt
cmake/FpMath.cmake
include/common/config.h.in
include/common/fixed.hpp
include/common/qrack_functions.hpp
include/common/qrack_types.hpp
include/qbdt.hpp
include/qbdt_node.hpp
include/qbdt_node_interface.hpp
src/common/fixed.cpp
src/common/functions.cpp
src/qbdt/node.cpp
src/qbdt/node_interface.cpp
src/qbdt/tree.cpp

We had a "false start" with fixed-point math: I added the relevant header but did not properly call its API the way I thought I had. Addressing this issue, it seems that fixed-point state vector simulation might be difficult and not necessarily better than floating-point. However, QBDD is an ideal candidate for fixed-point math, since branch pairs always exist in sets of two whose overall sum norm is 1, implying an absolute scale of 0.5 (or sqrt(0.5)) for all QBDD math.

Fixed-point for QBDD

---

CMakeLists.txt
README.md
doxygen.config
include/pinvoke_api.hpp
include/qfactory.hpp
include/qinterface.hpp
include/qinterface_noisy.hpp
include/qtensornetwork.hpp
include/wasm_api.hpp
src/pinvoke_api.cpp
src/qinterface_noisy.cpp
src/wasm_api.cpp

This adds a simulation layer with support for a very basic noise model: every gate applies single-qubit depolarizing noise on each qubit involved, respectively, based upon a noise parameter that can be set in code or by environment variable, between each single gate.

QInterfaceNoisy

---

include/qinterface.hpp
include/qinterface_noisy.hpp
src/qinterface/gates.cpp

I had two forms of ("weak") depolarizing noise in Qrack. One was just canonical stochastic Pauli noise. The other was a "trick" that I thought was clever to notice was equivalent. Turns out, the "trick" was _not_ equivalent. At some point, in refactoring Qrack for other reasons, I replaced the stochastic Pauli noise channel with the incorrect "trick," throughout. Stochastic Pauli noise _does_ reproduce depolarizing noise statistics and works just fine, here.

Noise debug

---

.github/workflows/build.yml
include/qstabilizer.hpp
src/qstabilizer.cpp
src/qunitclifford.cpp
test/tests.hpp

This PR greatly improves stabilizer performance, by using `boost::dynamic_bitset<>` and converting between transposed forms of the stabilizer tableau, so that both unitary operations and measurement can have efficient data locality.

Bitset stabilizer

---

CMakeLists.txt
include/pinvoke_api.hpp
include/qengine_cpu.hpp
include/qengine_cuda.hpp
include/qengine_opencl.hpp
include/qinterface.hpp
include/qpager.hpp
include/qstabilizer.hpp
include/qstabilizerhybrid.hpp
include/qtensornetwork.hpp
include/qunit.hpp
scripts/maxcut_approx.py
scripts/maxcut_np-complete.py
src/pinvoke_api.cpp
src/qengine/cuda.cu
src/qengine/opencl.cpp
src/qengine/state.cpp
src/qpager.cpp
src/qstabilizer.cpp
src/qunit.cpp
test/tests.cpp

This PR adds a method to (efficiently) retrieve the bit string in the simulator Hilbert space with the overall highest probability.

Highest probability method
