- _build/CTestTestfile.cmake
- include/qregister.hpp
- include/qregister_opencl.hpp
- src/qregister.cpp
- src/qregister_opencl.cpp
- src/qregister_software.cpp
- test/tests.cpp
depth_optimization is stable and will be merged into separated_unit_bugs.
> Depth optimization

- src/common/complex16simd.cpp
- src/qengine/state/opencl.cpp
The speed of complex multiplication has been increased. (Shuffles are cheaper than a cast to a vector type.) The change has been profiled with operf.
> Faster complex multiplication

- cmake/OpenCL.cmake
- include/common/oclengine.hpp
- include/qengine_cpu.hpp
- include/qengine_opencl_multi.hpp
- src/common/oclengine.cpp
- src/qengine/state/opencl_multi.cpp
- src/qengine/state/state.cpp
This adds OpenCL device selection and a simple form of load balancing to QEngineOCLMulti.
> OpenCL Device Selection

- CMakeLists.txt
- cmake/OpenCL.cmake
- include/common/oclengine.hpp
- include/qfactory.hpp
- include/qinterface.hpp
- include/qunit.hpp
- include/qunitmulti.hpp
- src/qunit.cpp
- src/qunitmulti.cpp
- test/test_main.cpp
This PR is just to pull the head of the master branch into a pull request opened before another merge.
> QUnitMulti into working branch

- README.md
- include/common/bitbuffer.hpp
- include/qengine_opencl.hpp
- include/qfusion.hpp
- include/qunitmulti.hpp
- src/common/bitbuffer.cpp
- src/qengine/opencl.cpp
- src/qfusion.cpp
- src/qunitmulti.cpp
(Merged last pull on the branch after closing it.)
> Qfusion optimization

- test/benchmarks.cpp
- test/test_main.cpp
* Adding new layer to benchmarks
* Adding default layer test_main.cpp
> Wrathful spatula patch 1 (#100)

- include/qunit.hpp
- src/qengine/qengine.cpp
- src/qunit.cpp
- test/benchmarks.cpp
(Working branches merge, not yet ready for PR on master)
> Schmidt decomposition

- src/qengine/opencl.cpp
When this WIP is finished, common OpenCL buffer operations will be moved into atomic and easier-to-read macros.
> Enqueued Buffer Operation Macros

- README.md
- include/qinterface.hpp
- src/qinterface/qinterface.cpp
- test/benchmarks.cpp
This is proofreading for the Doxygen. v3.1 will include up-to-date documentation.
> Doxygen edit

- CHANGELOG.md
- src/common/parallel_for.cpp
This will address issues with the OSX Mojave build, thanks to twobombs on #127 .
> Debugging OSX Mojave build

- include/common/oclengine.hpp
- include/qengine_cpu.hpp
- include/qengine_opencl.hpp
- src/qengine/opencl.cpp
- src/qinterface/protected.cpp
- test/tests.hpp
> OpenCL refactor and wider platform support

- CHANGELOG.md
I'm adding this to the change log and moving the tag forward one commit.
> Updating CHANGELOG.md for vm6502q.v3.1 release

- src/qunit.cpp
- test/benchmarks.cpp
Let me know if this satisfies the code duplication concerns.
Yes, we need these wrapper pass-throughs, to hit optimized cases. However, this is much less duplication.
> ApplyEitherControlled refactor

- README.md
- src/qengine/opencl.cpp
> Cleanup: Font info and tiny bug

- .travis.yml
Testing for ProjectQ support has been added to the CI, and passes.
> Projectq CI

- examples/shors_factoring.cpp
- src/qunit.cpp
The Shor's factoring algorithm example has been corrected, in the last step of the period finding subroutine. This exposed a set of bugs in QUnit, affecting "...ModN" arithmetic gates developed specifically for Shor's algorithm. These have also been corrected.
> Shor's factoring algorithm example debugging

- include/qengine.hpp
- include/qengine_cpu.hpp
- include/qengine_opencl.hpp
- include/qunit.hpp
- src/common/qengine.cl
- src/qengine/arithmetic.cpp
- src/qengine/opencl.cpp
- src/qengine/state.cpp
- src/qunit.cpp
The point is this PR is to reduce lines of code and increase code reuse. I'm going through by memory, trying to remember where the really tangled code is. I'll hack this out to reasonable point, test on all my test devices, and merge.
> Refactoring

- .travis.yml
Something changed about the CI under my nose, between the last commit in the last PR and merging, which broke the Python for the ProjectQ fork.
Let's try this again. Hopefully, the ProjectQ phase estimation algorithm tests don't under-perform and fail.
> Travis CI Python update

- src/qengine/opencl.cpp
- src/qinterface/protected.cpp
This PR fixes the regression in the Windows build. It has been tested on both Windows and Linux systems.
> Cleanup of Windows build

- README.md
This adds the badge provided by zenodo.org for DOI reference.
@bennbollay, do you approve?
> Adding DOI badge

- include/qunit.hpp
- src/qunit.cpp
- test/tests.cpp
I caught a couple of bugs, in the process of experimenting with extending CNOT optimizations. These should be merged, before continuing.
> Minor bug fixes

- README.md
- src/common/parallel_for.cpp
- src/qunit.cpp
- test/tests.cpp
Many thanks to the Unitary Fund, for its generous support! With their grant, we will be producing an article to help standardize benchmarks across quantum computer simulators!
I was trying to extend towards Gottesman-Knill, last night, but I realized my initial approach wouldn't work. However, the attempt led me to tweak performance and add coverage. These changes should also go in, but they're otherwise orphaned work, for now, so I'm including those changes here with the badge.
> Unitary Fund badge (with a minor performance "tweak" and coverage)

- src/qunit.cpp
(This is a PR across different development forks. I wanted to see the results of CI before including in another open PR.)
> Removing some PopHBasis2Qb() instances

- include/qunit.hpp
- src/qunit.cpp
(This is a PR between development branches.)
> Universal optimization

- include/qunit.hpp
Benn, this is so minute and self-apparent, I'm just going to slide this in without review if you don't get to it by the time the CI finishes.
> Fixed Raspberry Pi 3 unit tests

- include/qinterface.hpp
- include/qunit.hpp
- src/qunit.cpp
CCNOT should attempt the same `TryCnotOptimize()` as arbitrarily controlled "inversions."
> CCNOT optimize to CNOT or X; ApplySingleBit optimize to H

- include/qengine_opencl.hpp
- src/qengine/opencl.cpp
- src/qunitmulti.cpp
This should improve performance slightly, and it also seems to improve QUnitMulti stability on my heterogeneous system.
> Optimizing OpenCL LockSync()

- include/statevector.hpp
In the last PR, I switched the sparse state vector to use a  `std::unordered_map`. The unofficial GCC 128-bit unsigned integer does not support this, on my system. (GCC doesn't know how to hash it.) A `std::map` instead works.
> Fixing ENABLE_UINT128 build

- include/qunit.hpp
- src/qunit.cpp
- test/benchmarks.cpp
`real1` angle tracking has been replaced with `complex` phase factors, in `QUnit` controlled phase gate buffering.
> Issue #319: Fix phase buffer float denormalization

- include/qengine_cpu.hpp
- include/qengine_opencl.hpp
- include/qfusion.hpp
- include/qinterface.hpp
- include/qunit.hpp
- src/qengine/opencl.cpp
- src/qengine/state.cpp
- src/qfusion.cpp
- src/qinterface/qinterface.cpp
- src/qunit.cpp
- test/tests.cpp
Testing across multiple platforms has helped us identify more bugs. (See also #327.) We're testing general platform support before release, now.
> Remove TryDecompose; refactor TrySeparate(); remove isConsumed argument from Compose

- include/qunit.hpp
- src/qunit.cpp
The optimization approach of #333 And #334 can be extended to controlled phase gate optimizations. This has been tested as in those other PRs.
> CZ and ApplyControlledSinglePhase optimization

- .travis.yml
- src/qunit.cpp
An optimization case was missed in #336. This does not impact correctness, but this PR can improve performance.
> Missed cached |1> phase optimization

- src/qunit.cpp
This is an incremental improvement in the commutation rules of `QUnit::CommuteH()`, and a refactor of that method.
> CommuteH() improvement

- test/benchmarks.cpp
- test/tests.cpp
Per issue #351, the couplers in the Sycamore circuit benchmark need to be updated. I will follow up by updating the benchmark documentation page, this weekend or early in next week.
> Simplifying and debugging Sycamore circuit couplers, per issue #351

- include/qunit.hpp
- src/qunit.cpp
While tinkering with regard to #357, I found I could significantly improve QUnit::CommuteH(). Diagnosing #357 is still ongoing. (It's possible that the divergence between the QUnit and raw QEngine types is not even due to a logical error in implementation, if we had arbitrary numerical precision, though that honestly seems less likely to me.)
> CommuteH optimization

- src/qunit.cpp
If Schmidt decomposition succeeds for 1 qubit in a `QEngine` of 2 total qubits, under `QUnit`, then it makes sense to immediately refresh the cache for the other qubit in the `QEngine`, as well.
> Optimize 2 qubit ProbBase() checks

- include/qunit.hpp
- src/qunit.cpp
This PR is an incremental expansion on H gate commutation.
> More H gate commutation

- examples/qneuron_classification.cpp
Seeing as I am already speaking of "ROC" and "AUC," and these are necessary for evaluating cross validated fits, it makes sense to add an example of calculating them, here.
> Updating qneuron_classification example

- examples/qneuron_classification.cpp
- include/qneuron.hpp
In the `qneuron_classification` example, it's helpful to have logical segments of the program in imperative function scopes.
> QNeuron classification refactor

- src/qunit.cpp
It's becoming clear I've hit a wall in `QUnit` with phase/inversion buffer optimization. I'm reading more about stabilizer circuits, and I'm excited to incorporate the large body of work on their simulation into Qrack, if it will actually help `QUnit` give a further return. (Aaronson's CHP can simulate thousands of qubits on a single consumer-grade node, but then so can `QUnit`, under a different set of limitations, and I'm not yet totally sure what all the practical limitations and caveats of stabilizer simulation might be.)
In the mean time, I simply want to tidy up recent work. This PR is just a minor refactor, to reset for new feature research.
> Refactor of #392

- include/qunit.hpp
- src/qunit.cpp
`QUnit::TransformBasis1Qb()` was only ever used for reverting the basis, hence the argument for the opposite transformation can be removed.
> Remove unused argument from TransformBasis1Qb

- src/qunit.cpp
I've let some optimizations enacted elsewhere lapse in certain `QUnit` methods. These have been tested by swapping these methods into the cross entropy benchmarks, increasing the depth to 5, and increasing the iterations to 2000.
> Refactor QUnit for performance

- include/qunit.hpp
Earlier on, I figured "more parallelism is basically always better." However, in considering practical designs for potential industrial application of Qrack, it's best for the moment that `QEngine` is as `async` model as possible and that `QUnit` is serial, if this is the only CPU parallelism in the entirety of `QUnit`, removed in this PR. Performance does not suffer; it's better not juggle threads unless a demonstrable gain in speed can be made.
> Remove ParallelFor inheritance from QEngineShard

- src/common/qengine.cl
I happened to look at the intermediate representation (assembly) files generated for the OpenCL kernels on my development system. Most of it looks good, but the decomposeprob kernel is extremely unwieldy, whereas this is a particularly important API. QUnit focuses on proactive reduction of representational entanglement, and it does not frequently Decompose() in-flight representations, except after operations like measurement, but we should prioritize the Decompose() method for optimization. It's probably a good candidate to simplify, given its current level of complexity.
(I had the wrong branch in #404.)
> Define constants in Decompose() kernel

- src/qengine/opencl.cpp
Early in development of `QEngineOCL`, I unnecessarily complicated cross-device operation: buffer migration between devices (and even platforms) should be transparent and automatic, whether they need to be copied into an intermediate buffer on the host to cross platforms. While there can be advantages to manual migration, (and while there are API methods specifically for this purpose, which I overlooked,) there is no particular advantage that my old method for doing it intends, here. (Honestly, I simply thought this was bare requisite for inter-platform buffer migration, at the time, though it's fantastic that it's not.)
> Don't reimplement OpenCL buffer migration transparency

- src/qpager.cpp
I'm currently running benchmarks for QPager, and this branch will have slightly tuned parameters for performance.
> Tune default QPager threshold for OpenCL

- include/common/oclengine.hpp
- include/qengine_opencl.hpp
- src/qengine/opencl.cpp
- src/qpager.cpp
There's a bug at the interface of `QPager` and `QUnitMulti`, and it looks like it involves not properly handling the case of deallocated zero amplitudes, with full generality.
> SetDevice() should respect ZeroAmplitudes()

- src/qengine/opencl.cpp
(Sorry for the instability, today.) Temporarily, I need to revert certain changes, toward stability for layering `QPager` under `QUnit`, in  order to fix bugs I introduced in `QEngineOCL` in the process. So long as everything but `QPager` is working according to usual expectation, I will merge this PR, but hopefully I'll correct `QPager` as well, today.
> Partially revert commits from today, debug QPager and QEngineOCL

- include/qengine_cpu.hpp
- src/qengine/arithmetic.cpp
- src/qengine/gates.cpp
- src/qengine/opencl.cpp
- src/qengine/state.cpp
- src/qpager.cpp
This branch optimizes `QPager::SingleBitGate()`.
> QPager::SingleBitGate() optimization

- include/hamiltonian.hpp
- include/pinvoke_api.hpp
- src/pinvoke_api.cpp
This adds `TimeEvolve()` to the DLL API. (See #445.)
> DLL TimeEvolve()

- CMakeLists.txt
- include/statevector.hpp
- src/pinvoke_api.cpp
- src/qinterface/protected.cpp
- src/qpager.cpp
- test/tests.cpp
I'm experimenting with Android NDK builds. With these changes, we should build in a native C++11 Android Studio project. In `build.gradle`:
```
externalNativeBuild {
cmake {
cppFlags "-std=c++11"
arguments "-DENABLE_OPENCL=OFF", "-DENABLE_COMPLEX_X2=OFF", "-DENABLE_RDRAND=OFF"
targets "qrack", "qrack_pinvoke"
}
}
```
> Debugging for Android NDK

- src/common/parallel_for.cpp
Android Studio informs me that it's not necessary to capture "Stride," in the last PR.
> Not necessary to capture Stride

- .travis.yml
- CMakeLists.txt
- cmake/Complex_x2.cmake
- cmake/QUnit_CPU_Parallel.cmake
- include/common/config.h.in
- include/common/dispatchqueue.hpp
- include/qengine_cpu.hpp
- src/common/dispatchqueue.cpp
- src/qengine/state.cpp
I'm still experimenting with a dispatch queue that doesn't block on subsequent calls, but more methods can be added to the work of the previous few PRs.
> More async QEngineCPU methods

- CMakeLists.txt
- include/qengine.hpp
- include/qengine_cpu.hpp
- include/qengine_opencl.hpp
- include/qfactory.hpp
- include/qhybrid.hpp
- include/qinterface.hpp
- include/qpager.hpp
- include/statevector.hpp
- src/qhybrid.cpp
- src/qpager.cpp
- test/benchmarks_main.cpp
- test/test_main.cpp
- test/tests.cpp
Per #460, this implements the `Qrack::QHybrid` type. It's functioning, but I'm still optimizing.
> WIP: QHybrid

- src/qunit.cpp
- test/benchmarks.cpp
Based on benchmarks so far, this appears to improve the efficiency of CNOT. When CI passes, if further benchmarks continue to show an improvement, this will be merged.
> CNOT optimization

- include/qstabilizer.hpp
- include/qstabilizerhybrid.hpp
- src/qstabilizer.cpp
It looks like I've fixed nonspecific bugs that allow us to support a layering of QUnit over QStabilizerHybrid, now, but not to the end of practical performance improvements, yet.
> QUnit -> QStabilizerHybrid stack

- src/qunit.cpp
This edge case might not exist, but if a buffer exists between control and target qubits in the same "unit," then they should be flushed before applying a new gate between these two qubits.
> Don't except control from buffer flushing if IS_SAME_UNIT()

- include/qinterface.hpp
- include/qstabilizerhybrid.hpp
- include/qunit.hpp
- src/qstabilizerhybrid.cpp
- src/qunit.cpp
- test/benchmarks.cpp
- test/benchmarks_main.cpp
- test/test_main.cpp
- test/tests.cpp
This covers and optimizes certain QStabilizerHybrid edge cases.
> Missing QStabilizerHybrid edge cases

- include/qinterface.hpp
- include/qstabilizer.hpp
- src/qstabilizer.cpp
This fixes the build for Android.
> Android debugging: virtual destructors, and compile variant debugging

- include/qunit.hpp
- src/qunit.cpp
- test/benchmarks_main.cpp
This addresses various issues brought up about benchmarks, in our Discord channel. An issue ticket has been opened for conversion to built-in Catch2 benchmark features, as well, which will follow this PR.
> Benchmark debugging

- .travis.yml
- include/pinvoke_api.hpp
- src/pinvoke_api.cpp
- src/qunit.cpp
This branch contains the changes to the base Qrack API necessary to support corresponding changes in the integration package for Q#.
> Q# debugging and additional intrinsics overrides

- src/qunit.cpp
`QUnit::MAll()` appears to have a segfault in its implementation. Most of the performance gains of the method can be recovered with a much simpler implementation.
> Temporarily skip optimized implementation of QUnit:MAll()

- include/qunit.hpp
- src/qinterface/gates.cpp
- src/qunit.cpp
- test/tests.cpp
This PR completes the work of the closed #542. I'm still testing with all of our plugins, but Q# works.
> QUnit Pauli Y basis

- include/qunit.hpp
- src/qunit.cpp
I'm "tweaking" stabilizer interface with QUnit. The cases covered here might not give a general performance improvement, but I think the refactor should be accepted.
> Stabilizer optimization

- src/pinvoke_api.cpp
Changing my iOS build target to 12.0, I encounter more warnings/errors. This PR fixes these. I might iterate through some more of the available version targets of iOS and try to fix the build for all of them.
> Debugging PInvoke DLL for iOS 12

- include/qfactory.hpp
- src/qpager.cpp
- src/qstabilizerhybrid.cpp
- test/benchmarks_main.cpp
- test/test_main.cpp
This adds optimized QPager "decomposition" methods, which I am still testing and considering. It also makes some bug fixes in the test suites.
> QPager decomposition optimization

- src/qpager.cpp
Having coincidentally found and mixed "front" and "back" cases for `Compose()`/`Decompose()`/`Dispose()`, and seeing as both approaches work, we can optimize all three methods with two different "tail" cases. This basically reduces the maximum page concatenation level by half.
> Split QPager Compose/Decompose/Dispose cases for efficiency

- include/qengine_opencl.hpp
- src/common/qengine.cl
- src/qengine/opencl.cpp
- test/tests.hpp
This fixes the bug in one of the `Dispose()` variants, on the Intel HD.
> Dispose debug

- .travis.yml
- CMakeLists.txt
- cmake/Complex8.cmake
- cmake/FpPow.cmake
- cmake/QbCapPow.cmake
- cmake/UInt.cmake
- cmake/UIntPow.cmake
- include/common/config.h.in
- include/common/qrack_types.hpp
- src/common/oclengine.cpp
- src/common/qheader_double.cl
- src/common/qheader_half.cl
- src/common/qheader_uint16.cl
- src/common/qheader_uint32.cl
- src/common/qheader_uint64.cl
- src/qengine/state.cpp
Per #620, the build interface has been updated to independently switch between floating point and unsigned integer "real1" and "bitCapInt" types.
> Independent FP/UINT switching

- src/qpager.cpp
- test/tests.cpp
This is partial work toward debugging the unit test failures that have crept into `QPager`.
> QPager Decompose()/Dispose() debugging and Uniform gate optimization

- src/qpager.cpp
Per issue #635, `QPager` parallelism that is redundant with the asynchronous design of `QInterface` is removed.
> Remove QInterface-redundant QPager parallelism

- .travis.yml
- include/common/qrack_types.hpp
- include/qengineshard.hpp
- src/common/qheader_double.cl
- src/common/qheader_float.cl
- src/common/qheader_half.cl
- src/qunit.cpp
- test/tests.cpp
This has been opened in favor over #643.
> Floating point rounding

- include/qpager.hpp
- src/qengine/qengine.cpp
- src/qinterface/gates.cpp
- src/qpager.cpp
This is cleaner incremental work toward the goal of #653.
> Refactor ZeroPhaseFlip(); correct QEngine FP rounding

- src/qpager.cpp
We are incrementally moving toward resolving the goal of #653, by figuring out why the default `ZeroPhaseFlip()` implementation in `QPager` doesn't work with a `QUnit` layer over it.
> Restore optimized QPager::ZeroPhaseFlip()

- include/qpager.hpp
- src/qpager.cpp
This PR starts to make a `QUnit`->`QPager` stack practical for general use case, by intelligently changing `QPager` paging threshold in flight and better optimizing `QPager::Compose()` for a paged case.
> QUnit->QPager stack

- include/qengineshard.hpp
- include/qinterface.hpp
- include/qstabilizerhybrid.hpp
- include/qunit.hpp
- src/qunit.cpp
This is cleaning up the work of the last few PRs, for extended stabilizer simulation.
> Optimize non-Clifford buffering

- include/pinvoke_api.hpp
- include/qinterface.hpp
- src/pinvoke_api.cpp
- src/qinterface/qinterface.cpp
This exposes the QFT algorithm via DLL, to avoid unnecessary reimplementation, and for experimentation.
> PInvoke QFT

- include/qinterface.hpp
- include/qstabilizerhybrid.hpp
- src/pinvoke_api.cpp
- src/qstabilizerhybrid.cpp
This further extends stabilizer optimization, to recover additional Pauli X and Y basis cases.
> Extended stabilizer X/Y/Z basis optimization

- src/common/oclengine.cpp
This reuses the same OpenCL intermediate representation or binary when precompiling kernels for multi-OpenCL-device systems. (I need to spin up an AWS EC2 instance to test this, later tonight.)
> Reuse OCL binary for same device types

- src/qunit.cpp
This simplifies `QUnit` bit separation code.
> Refactor separation

- include/qunit.hpp
- src/qunit.cpp
These variants were lower priority, for a long time, but they need back-filling, now.
> Anti-CY/CZ QUnit variants

- src/qunit.cpp
It no longer seems like a long-shot optimization, that single bit basis transformation in `QUnit` could produce a phase or "inversion" gate.
> Optimize QUnit single bit gates

- include/qstabilizerhybrid.hpp
Composing single bit fusion buffers allows diversion into `ApplySinglePhase()` and `ApplySingleInvert()`.
> ComposeGate()

- test/benchmarks.cpp
Rather than spitting out the (identical) exception message for every benchmark trial failure, on over-width trials, it's better to simply add a failure count column.
> Add benchmark failure count column

- include/qpager.hpp
- include/qunit.hpp
- src/qengine/opencl.cpp
- src/qengine/state.cpp
- src/qinterface/qinterface.cpp
- src/qpager.cpp
- src/qunit.cpp
This is a preparatory refactor for optimization work in single-qubit `TrySeparate()`.
> QPager::ApproxCompare() optimize

- include/qstabilizer.hpp
- src/qengine/opencl.cpp
- src/qstabilizer.cpp
- src/qstabilizerhybrid.cpp
> More efficient stabilizer conversion to key (and OCL SetAmplitude bug fix)

- src/qpager.cpp
- test/tests.hpp
Per #824, there still seems to be a second smaller bug in `QPager::Prob()`, but I'm working on it. This isn't an ideal fix, but it's high priority.
> CombineEngine() before Compose()

- src/qstabilizerhybrid.cpp
- test/tests.cpp
> Test mirror circuit 8

- include/qengine_opencl.hpp
- src/qengine/opencl.cpp
- src/qengine/state.cpp
- src/qpager.cpp
Over the next few days, I will be debugging `QUnit` over `QPager`. This entails fixing denormalized operation of `QEngine` types. This PR is incremental cleanup refactor work, for tonight.
> `QPager` debug

- include/qengine_cpu.hpp
- include/qengine_opencl.hpp
- src/qengine/opencl.cpp
- src/qengine/state.cpp
This is a small refactor on `QEngine` methods and functionality used by `QPager`.
> `QEngine`/`QPager` refactor

- examples/grovers_lookup.cpp
- include/common/qrack_types.hpp
- include/hamiltonian.hpp
- include/qengine.hpp
- include/qengineshard.hpp
- include/qhybrid.hpp
- include/qinterface.hpp
- include/qneuron.hpp
- include/qstabilizerhybrid.hpp
- include/qunit.hpp
- include/qunitmulti.hpp
- src/pinvoke_api.cpp
- src/qengine/state.cpp
- src/qinterface/gates.cpp
- src/qinterface/qinterface.cpp
- src/qpager.cpp
- src/qstabilizer.cpp
- src/qunit.cpp
- src/qunitmulti.cpp
Hopefully, this addresses every single alert, from LGTM.
> Fix LGTM alerts

- include/pinvoke_api.hpp
- include/qinterface.hpp
- src/pinvoke_api.cpp
- src/qinterface/rotational.cpp
> #872: Expose anti-controlled operations in DLL, and refactor

- src/pinvoke_api.cpp
It seems like PyQrack is holding onto simulator instance garbage after destructors are called, but this is likely in the shared library itself, and the obvious suspects are the maps by (`shared_ptr`) `QInterfacePtr`. I'm testing, right now, whether removing these strong references lets garbage be disposed. I would use a `weak_ptr` rather than a raw pointer, and I have to apologize for that, but `weak_ptr` doesn't seem have ordering operators that allow it to be used as the keys of `std::map`, at least in C++11. However, it'll be obvious fairly quickly whether this change lets us release garbage, and we don't access these maps' keys in iteration over key-value pairs, (only values).
This is subject to change, but it will probably be accepted as-is, if tests in progress remain stable.
> Don't hold strong references to QInterfacePtr in maps

- include/hamiltonian.hpp
- include/qengine.hpp
- include/qinterface.hpp
- include/statevector.hpp
The Visual Studio warnings are all valuable. However, some are easier than others to resolve, or more important. (This PR absolutely has to wait on LGTM CI.)
> Fix unobjectionable Windows warnings, (plan for resolving others)

- include/qengineshard.hpp
- src/qunit.cpp
These are the last of the Visual Studio warnings to fix, for now.
> Fix more VS warnings

- src/qbinary_decision_tree/tree.cpp
- src/qengine/qengine.cpp
- src/qengine/state.cpp
- src/qinterface/arithmetic.cpp
- src/qinterface/protected.cpp
- src/qinterface/rotational.cpp
- test/accuracy.cpp
- test/accuracy_main.cpp
- test/tests.cpp
Always use `CMPLX` macros, when applicable.
> CMPLX macros

- include/common/oclengine.hpp
- include/qunitmulti.hpp
- src/common/parallel_for.cpp
- src/qengine/state.cpp
- src/qhybrid.cpp
- src/qpager.cpp
- src/qunitmulti.cpp
(... And `PSTRIDEPOW` constant type handling)
> OpenCL device ID safety

- .github/workflows/cmake.yml
Let's start by printing the CI output to log, and maybe this is the better configuration in general.
> WIP: Debug CI

- include/qstabilizer.hpp
- src/qstabilizer.cpp
- src/qstabilizerhybrid.cpp
This adds optimized `AntiCNOT()`, `AntiCY()`, and `AntiCZ()` cases to `QStabilizer`.
> Stabilizer MACMtrx

- CMakeLists.txt
- doxygen.config
- examples/qneuron_classification.cpp
- examples/quantum_associative_memory.cpp
- examples/quantum_perceptron.cpp
- include/pinvoke_api.hpp
- include/qneuron.hpp
- src/pinvoke_api.cpp
This PR exposes the `QNeuron` interface through the shared library, for consumption by PyQrack and other external software.
> QNeuron shared library api

- cmake/Alu.cmake
- include/qcircuit.hpp
- src/arithmetic_qcircuit.cpp
- test/tests.cpp
create pr for qcircuit - INC impl and tests
> unitaryhack - Extend QCircuit to QInterface #988

- include/pinvoke_api.hpp
- include/qinterface.hpp
- include/qstabilizerhybrid.hpp
- src/pinvoke_api.cpp
- src/qstabilizerhybrid.cpp
This adds an _approximate_ sampling option to `QStabilizerHybrid`.
> Hybrid stabilizer approximate sampling

- include/qstabilizer.hpp
- src/qstabilizer.cpp
- test/tests.cpp
This fixes phase-awareness in stabilizer simulation, for measurement and `CY`.
> Phase-aware stabilizer
